#ifndef GUARD_CONSTANTS_WEATHER_H
#define GUARD_CONSTANTS_WEATHER_H

enum {
    WEATHER_NONE,
    WEATHER_CLOUDS,
    WEATHER_SUNNY,
    WEATHER_RAIN_LIGHT,
    WEATHER_SNOW,
    WEATHER_RAIN_MED,
    WEATHER_FOG_1,
    WEATHER_ASH,
    WEATHER_SANDSTORM,
    WEATHER_FOG_2,
    WEATHER_FOG_3,
    WEATHER_SHADE,
    WEATHER_DROUGHT,
    WEATHER_RAIN_HEAVY,
    WEATHER_BUBBLES,
    WEATHER_ROUTE119_CYCLE = 20,
    WEATHER_ROUTE123_CYCLE
};

// These are used in maps' coord_weather_event entries.
// They are not a one-to-one mapping with the engine's
// internal weather constants above.
enum {
    COORD_EVENT_WEATHER_CLOUDS,
    COORD_EVENT_WEATHER_SUNNY,
    COORD_EVENT_WEATHER_RAIN_LIGHT,
    COORD_EVENT_WEATHER_SNOW,
    COORD_EVENT_WEATHER_RAIN_MED,
    COORD_EVENT_WEATHER_FOG_1,
    COORD_EVENT_WEATHER_FOG_2,
    COORD_EVENT_WEATHER_ASH,
    COORD_EVENT_WEATHER_SANDSTORM,
    COORD_EVENT_WEATHER_SHADE,
    COORD_EVENT_WEATHER_DROUGHT,
    COORD_EVENT_WEATHER_ROUTE119_CYCLE = 20,
    COORD_EVENT_WEATHER_ROUTE123_CYCLE
};

#endif  // GUARD_CONSTANTS_WEATHER_H
