PetalburgCity_MapBorder::
	.incbin "data/maps/PetalburgCity/border.bin"

PetalburgCity_MapBlockdata::
	.incbin "data/maps/PetalburgCity/map.bin"

	.align 2
PetalburgCity_MapAttributes::
	.4byte 0x1e
	.4byte 0x1e
	.4byte PetalburgCity_MapBorder
	.4byte PetalburgCity_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Petalburg

SlateportCity_MapBorder::
	.incbin "data/maps/SlateportCity/border.bin"

SlateportCity_MapBlockdata::
	.incbin "data/maps/SlateportCity/map.bin"

	.align 2
SlateportCity_MapAttributes::
	.4byte 0x28
	.4byte 0x3c
	.4byte SlateportCity_MapBorder
	.4byte SlateportCity_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Slateport

MauvilleCity_MapBorder::
	.incbin "data/maps/MauvilleCity/border.bin"

MauvilleCity_MapBlockdata::
	.incbin "data/maps/MauvilleCity/map.bin"

	.align 2
MauvilleCity_MapAttributes::
	.4byte 0x28
	.4byte 0x14
	.4byte MauvilleCity_MapBorder
	.4byte MauvilleCity_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Mauville

RustboroCity_MapBorder::
	.incbin "data/maps/RustboroCity/border.bin"

RustboroCity_MapBlockdata::
	.incbin "data/maps/RustboroCity/map.bin"

	.align 2
RustboroCity_MapAttributes::
	.4byte 0x28
	.4byte 0x3c
	.4byte RustboroCity_MapBorder
	.4byte RustboroCity_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Rustboro

FortreeCity_MapBorder::
	.incbin "data/maps/FortreeCity/border.bin"

FortreeCity_MapBlockdata::
	.incbin "data/maps/FortreeCity/map.bin"

	.align 2
FortreeCity_MapAttributes::
	.4byte 0x28
	.4byte 0x14
	.4byte FortreeCity_MapBorder
	.4byte FortreeCity_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Fortree

LilycoveCity_MapBorder::
	.incbin "data/maps/LilycoveCity/border.bin"

LilycoveCity_MapBlockdata::
	.incbin "data/maps/LilycoveCity/map.bin"

	.align 2
LilycoveCity_MapAttributes::
	.4byte 0x50
	.4byte 0x28
	.4byte LilycoveCity_MapBorder
	.4byte LilycoveCity_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Lilycove

MossdeepCity_MapBorder::
	.incbin "data/maps/MossdeepCity/border.bin"

MossdeepCity_MapBlockdata::
	.incbin "data/maps/MossdeepCity/map.bin"

	.align 2
MossdeepCity_MapAttributes::
	.4byte 0x50
	.4byte 0x28
	.4byte MossdeepCity_MapBorder
	.4byte MossdeepCity_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Mossdeep

SootopolisCity_MapBorder::
	.incbin "data/maps/SootopolisCity/border.bin"

SootopolisCity_MapBlockdata::
	.incbin "data/maps/SootopolisCity/map.bin"

	.align 2
SootopolisCity_MapAttributes::
	.4byte 0x3c
	.4byte 0x3c
	.4byte SootopolisCity_MapBorder
	.4byte SootopolisCity_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Sootopolis

EverGrandeCity_MapBorder::
	.incbin "data/maps/EverGrandeCity/border.bin"

EverGrandeCity_MapBlockdata::
	.incbin "data/maps/EverGrandeCity/map.bin"

	.align 2
EverGrandeCity_MapAttributes::
	.4byte 0x28
	.4byte 0x50
	.4byte EverGrandeCity_MapBorder
	.4byte EverGrandeCity_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_EverGrande

LittlerootTown_MapBorder::
	.incbin "data/maps/LittlerootTown/border.bin"

LittlerootTown_MapBlockdata::
	.incbin "data/maps/LittlerootTown/map.bin"

	.align 2
LittlerootTown_MapAttributes::
	.4byte 0x14
	.4byte 0x14
	.4byte LittlerootTown_MapBorder
	.4byte LittlerootTown_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Petalburg

OldaleTown_MapBorder::
	.incbin "data/maps/OldaleTown/border.bin"

OldaleTown_MapBlockdata::
	.incbin "data/maps/OldaleTown/map.bin"

	.align 2
OldaleTown_MapAttributes::
	.4byte 0x14
	.4byte 0x14
	.4byte OldaleTown_MapBorder
	.4byte OldaleTown_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Petalburg

DewfordTown_MapBorder::
	.incbin "data/maps/DewfordTown/border.bin"

DewfordTown_MapBlockdata::
	.incbin "data/maps/DewfordTown/map.bin"

	.align 2
DewfordTown_MapAttributes::
	.4byte 0x14
	.4byte 0x14
	.4byte DewfordTown_MapBorder
	.4byte DewfordTown_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Dewford

LavaridgeTown_MapBorder::
	.incbin "data/maps/LavaridgeTown/border.bin"

LavaridgeTown_MapBlockdata::
	.incbin "data/maps/LavaridgeTown/map.bin"

	.align 2
LavaridgeTown_MapAttributes::
	.4byte 0x14
	.4byte 0x14
	.4byte LavaridgeTown_MapBorder
	.4byte LavaridgeTown_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Lavaridge

FallarborTown_MapBorder::
	.incbin "data/maps/FallarborTown/border.bin"

FallarborTown_MapBlockdata::
	.incbin "data/maps/FallarborTown/map.bin"

	.align 2
FallarborTown_MapAttributes::
	.4byte 0x14
	.4byte 0x14
	.4byte FallarborTown_MapBorder
	.4byte FallarborTown_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Fallarbor

VerdanturfTown_MapBorder::
	.incbin "data/maps/VerdanturfTown/border.bin"

VerdanturfTown_MapBlockdata::
	.incbin "data/maps/VerdanturfTown/map.bin"

	.align 2
VerdanturfTown_MapAttributes::
	.4byte 0x14
	.4byte 0x14
	.4byte VerdanturfTown_MapBorder
	.4byte VerdanturfTown_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Mauville

PacifidlogTown_MapBorder::
	.incbin "data/maps/PacifidlogTown/border.bin"

PacifidlogTown_MapBlockdata::
	.incbin "data/maps/PacifidlogTown/map.bin"

	.align 2
PacifidlogTown_MapAttributes::
	.4byte 0x14
	.4byte 0x28
	.4byte PacifidlogTown_MapBorder
	.4byte PacifidlogTown_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Pacifidlog

Route101_MapBorder::
	.incbin "data/maps/Route101/border.bin"

Route101_MapBlockdata::
	.incbin "data/maps/Route101/map.bin"

	.align 2
Route101_MapAttributes::
	.4byte 0x14
	.4byte 0x14
	.4byte Route101_MapBorder
	.4byte Route101_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Petalburg

Route102_MapBorder::
	.incbin "data/maps/Route102/border.bin"

Route102_MapBlockdata::
	.incbin "data/maps/Route102/map.bin"

	.align 2
Route102_MapAttributes::
	.4byte 0x32
	.4byte 0x14
	.4byte Route102_MapBorder
	.4byte Route102_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Petalburg

Route103_MapBorder::
	.incbin "data/maps/Route103/border.bin"

Route103_MapBlockdata::
	.incbin "data/maps/Route103/map.bin"

	.align 2
Route103_MapAttributes::
	.4byte 0x50
	.4byte 0x14
	.4byte Route103_MapBorder
	.4byte Route103_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Petalburg

Route104_MapBorder::
	.incbin "data/maps/Route104/border.bin"

Route104_MapBlockdata::
	.incbin "data/maps/Route104/map.bin"

	.align 2
Route104_MapAttributes::
	.4byte 0x28
	.4byte 0x50
	.4byte Route104_MapBorder
	.4byte Route104_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Rustboro

Route105_MapBorder::
	.incbin "data/maps/Route105/border.bin"

Route105_MapBlockdata::
	.incbin "data/maps/Route105/map.bin"

	.align 2
Route105_MapAttributes::
	.4byte 0x28
	.4byte 0x50
	.4byte Route105_MapBorder
	.4byte Route105_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Dewford

Route106_MapBorder::
	.incbin "data/maps/Route106/border.bin"

Route106_MapBlockdata::
	.incbin "data/maps/Route106/map.bin"

	.align 2
Route106_MapAttributes::
	.4byte 0x50
	.4byte 0x14
	.4byte Route106_MapBorder
	.4byte Route106_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Dewford

Route107_MapBorder::
	.incbin "data/maps/Route107/border.bin"

Route107_MapBlockdata::
	.incbin "data/maps/Route107/map.bin"

	.align 2
Route107_MapAttributes::
	.4byte 0x3c
	.4byte 0x14
	.4byte Route107_MapBorder
	.4byte Route107_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Dewford

Route108_MapBorder::
	.incbin "data/maps/Route108/border.bin"

Route108_MapBlockdata::
	.incbin "data/maps/Route108/map.bin"

	.align 2
Route108_MapAttributes::
	.4byte 0x3c
	.4byte 0x14
	.4byte Route108_MapBorder
	.4byte Route108_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Slateport

Route109_MapBorder::
	.incbin "data/maps/Route109/border.bin"

Route109_MapBlockdata::
	.incbin "data/maps/Route109/map.bin"

	.align 2
Route109_MapAttributes::
	.4byte 0x28
	.4byte 0x3c
	.4byte Route109_MapBorder
	.4byte Route109_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Slateport

Route110_MapBorder::
	.incbin "data/maps/Route110/border.bin"

Route110_MapBlockdata::
	.incbin "data/maps/Route110/map.bin"

	.align 2
Route110_MapAttributes::
	.4byte 0x28
	.4byte 0x64
	.4byte Route110_MapBorder
	.4byte Route110_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Mauville

Route111_MapBorder::
	.incbin "data/maps/Route111/border.bin"

Route111_MapBlockdata::
	.incbin "data/maps/Route111/map.bin"

	.align 2
Route111_MapAttributes::
	.4byte 0x28
	.4byte 0x8c
	.4byte Route111_MapBorder
	.4byte Route111_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Mauville

Route112_MapBorder::
	.incbin "data/maps/Route112/border.bin"

Route112_MapBlockdata::
	.incbin "data/maps/Route112/map.bin"

	.align 2
Route112_MapAttributes::
	.4byte 0x28
	.4byte 0x3c
	.4byte Route112_MapBorder
	.4byte Route112_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Lavaridge

Route113_MapBorder::
	.incbin "data/maps/Route113/border.bin"

Route113_MapBlockdata::
	.incbin "data/maps/Route113/map.bin"

	.align 2
Route113_MapAttributes::
	.4byte 0x64
	.4byte 0x14
	.4byte Route113_MapBorder
	.4byte Route113_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Fallarbor

Route114_MapBorder::
	.incbin "data/maps/Route114/border.bin"

Route114_MapBlockdata::
	.incbin "data/maps/Route114/map.bin"

	.align 2
Route114_MapAttributes::
	.4byte 0x28
	.4byte 0x50
	.4byte Route114_MapBorder
	.4byte Route114_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Fallarbor

Route115_MapBorder::
	.incbin "data/maps/Route115/border.bin"

Route115_MapBlockdata::
	.incbin "data/maps/Route115/map.bin"

	.align 2
Route115_MapAttributes::
	.4byte 0x28
	.4byte 0x50
	.4byte Route115_MapBorder
	.4byte Route115_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Fallarbor

Route116_MapBorder::
	.incbin "data/maps/Route116/border.bin"

Route116_MapBlockdata::
	.incbin "data/maps/Route116/map.bin"

	.align 2
Route116_MapAttributes::
	.4byte 0x64
	.4byte 0x14
	.4byte Route116_MapBorder
	.4byte Route116_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Rustboro

Route117_MapBorder::
	.incbin "data/maps/Route117/border.bin"

Route117_MapBlockdata::
	.incbin "data/maps/Route117/map.bin"

	.align 2
Route117_MapAttributes::
	.4byte 0x3c
	.4byte 0x14
	.4byte Route117_MapBorder
	.4byte Route117_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Mauville

Route118_MapBorder::
	.incbin "data/maps/Route118/border.bin"

Route118_MapBlockdata::
	.incbin "data/maps/Route118/map.bin"

	.align 2
Route118_MapAttributes::
	.4byte 0x50
	.4byte 0x14
	.4byte Route118_MapBorder
	.4byte Route118_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Mauville

Route119_MapBorder::
	.incbin "data/maps/Route119/border.bin"

Route119_MapBlockdata::
	.incbin "data/maps/Route119/map.bin"

	.align 2
Route119_MapAttributes::
	.4byte 0x28
	.4byte 0x8c
	.4byte Route119_MapBorder
	.4byte Route119_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Fortree

Route120_MapBorder::
	.incbin "data/maps/Route120/border.bin"

Route120_MapBlockdata::
	.incbin "data/maps/Route120/map.bin"

	.align 2
Route120_MapAttributes::
	.4byte 0x28
	.4byte 0x64
	.4byte Route120_MapBorder
	.4byte Route120_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Fortree

Route121_MapBorder::
	.incbin "data/maps/Route121/border.bin"

Route121_MapBlockdata::
	.incbin "data/maps/Route121/map.bin"

	.align 2
Route121_MapAttributes::
	.4byte 0x50
	.4byte 0x14
	.4byte Route121_MapBorder
	.4byte Route121_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Lilycove

Route122_MapBorder::
	.incbin "data/maps/Route122/border.bin"

Route122_MapBlockdata::
	.incbin "data/maps/Route122/map.bin"

	.align 2
Route122_MapAttributes::
	.4byte 0x28
	.4byte 0x28
	.4byte Route122_MapBorder
	.4byte Route122_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Lilycove

Route123_MapBorder::
	.incbin "data/maps/Route123/border.bin"

Route123_MapBlockdata::
	.incbin "data/maps/Route123/map.bin"

	.align 2
Route123_MapAttributes::
	.4byte 0x8c
	.4byte 0x14
	.4byte Route123_MapBorder
	.4byte Route123_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Lilycove

Route124_MapBorder::
	.incbin "data/maps/Route124/border.bin"

Route124_MapBlockdata::
	.incbin "data/maps/Route124/map.bin"

	.align 2
Route124_MapAttributes::
	.4byte 0x50
	.4byte 0x50
	.4byte Route124_MapBorder
	.4byte Route124_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Mossdeep

Route125_MapBorder::
	.incbin "data/maps/Route125/border.bin"

Route125_MapBlockdata::
	.incbin "data/maps/Route125/map.bin"

	.align 2
Route125_MapAttributes::
	.4byte 0x50
	.4byte 0x28
	.4byte Route125_MapBorder
	.4byte Route125_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Mossdeep

Route126_MapBorder::
	.incbin "data/maps/Route126/border.bin"

Route126_MapBlockdata::
	.incbin "data/maps/Route126/map.bin"

	.align 2
Route126_MapAttributes::
	.4byte 0x50
	.4byte 0x50
	.4byte Route126_MapBorder
	.4byte Route126_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Mossdeep

Route127_MapBorder::
	.incbin "data/maps/Route127/border.bin"

Route127_MapBlockdata::
	.incbin "data/maps/Route127/map.bin"

	.align 2
Route127_MapAttributes::
	.4byte 0x50
	.4byte 0x50
	.4byte Route127_MapBorder
	.4byte Route127_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Mossdeep

Route128_MapBorder::
	.incbin "data/maps/Route128/border.bin"

Route128_MapBlockdata::
	.incbin "data/maps/Route128/map.bin"

	.align 2
Route128_MapAttributes::
	.4byte 0x78
	.4byte 0x28
	.4byte Route128_MapBorder
	.4byte Route128_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Mossdeep

Route129_MapBorder::
	.incbin "data/maps/Route129/border.bin"

Route129_MapBlockdata::
	.incbin "data/maps/Route129/map.bin"

	.align 2
Route129_MapAttributes::
	.4byte 0x50
	.4byte 0x28
	.4byte Route129_MapBorder
	.4byte Route129_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Mossdeep

UnreferencedMap_MapBorder::
	.incbin "data/maps/UnreferencedMap/border.bin"

UnreferencedMap_MapBlockdata::
	.incbin "data/maps/UnreferencedMap/map.bin"

	.align 2
UnreferencedMap_MapAttributes::
	.4byte 0x50
	.4byte 0x28
	.4byte UnreferencedMap_MapBorder
	.4byte UnreferencedMap_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Cave

Route131_MapBorder::
	.incbin "data/maps/Route131/border.bin"

Route131_MapBlockdata::
	.incbin "data/maps/Route131/map.bin"

	.align 2
Route131_MapAttributes::
	.4byte 0x3c
	.4byte 0x28
	.4byte Route131_MapBorder
	.4byte Route131_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Pacifidlog

Route132_MapBorder::
	.incbin "data/maps/Route132/border.bin"

Route132_MapBlockdata::
	.incbin "data/maps/Route132/map.bin"

	.align 2
Route132_MapAttributes::
	.4byte 0x50
	.4byte 0x28
	.4byte Route132_MapBorder
	.4byte Route132_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Pacifidlog

Route133_MapBorder::
	.incbin "data/maps/Route133/border.bin"

Route133_MapBlockdata::
	.incbin "data/maps/Route133/map.bin"

	.align 2
Route133_MapAttributes::
	.4byte 0x50
	.4byte 0x28
	.4byte Route133_MapBorder
	.4byte Route133_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Pacifidlog

Route134_MapBorder::
	.incbin "data/maps/Route134/border.bin"

Route134_MapBlockdata::
	.incbin "data/maps/Route134/map.bin"

	.align 2
Route134_MapAttributes::
	.4byte 0x50
	.4byte 0x28
	.4byte Route134_MapBorder
	.4byte Route134_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Pacifidlog

Underwater2_MapBorder::
	.incbin "data/maps/Underwater2/border.bin"

Underwater2_MapBlockdata::
	.incbin "data/maps/Underwater2/map.bin"

	.align 2
Underwater2_MapAttributes::
	.4byte 0x50
	.4byte 0x50
	.4byte Underwater2_MapBorder
	.4byte Underwater2_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Underwater

Underwater3_MapBorder::
	.incbin "data/maps/Underwater3/border.bin"

Underwater3_MapBlockdata::
	.incbin "data/maps/Underwater3/map.bin"

	.align 2
Underwater3_MapAttributes::
	.4byte 0x50
	.4byte 0x50
	.4byte Underwater3_MapBorder
	.4byte Underwater3_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Underwater

Underwater4_MapBorder::
	.incbin "data/maps/Underwater4/border.bin"

Underwater4_MapBlockdata::
	.incbin "data/maps/Underwater4/map.bin"

	.align 2
Underwater4_MapAttributes::
	.4byte 0x78
	.4byte 0x28
	.4byte Underwater4_MapBorder
	.4byte Underwater4_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Underwater

LittlerootTown_BrendansHouse_1F_MapBorder::
	.incbin "data/maps/LittlerootTown_BrendansHouse_1F/border.bin"

LittlerootTown_BrendansHouse_1F_MapBlockdata::
	.incbin "data/maps/LittlerootTown_BrendansHouse_1F/map.bin"

	.align 2
LittlerootTown_BrendansHouse_1F_MapAttributes::
	.4byte 0xb
	.4byte 0x9
	.4byte LittlerootTown_BrendansHouse_1F_MapBorder
	.4byte LittlerootTown_BrendansHouse_1F_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_BrendansMaysHouse

LittlerootTown_BrendansHouse_2F_MapBorder::
	.incbin "data/maps/LittlerootTown_BrendansHouse_2F/border.bin"

LittlerootTown_BrendansHouse_2F_MapBlockdata::
	.incbin "data/maps/LittlerootTown_BrendansHouse_2F/map.bin"

	.align 2
LittlerootTown_BrendansHouse_2F_MapAttributes::
	.4byte 0x9
	.4byte 0x8
	.4byte LittlerootTown_BrendansHouse_2F_MapBorder
	.4byte LittlerootTown_BrendansHouse_2F_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_BrendansMaysHouse

LittlerootTown_MaysHouse_1F_MapBorder::
	.incbin "data/maps/LittlerootTown_MaysHouse_1F/border.bin"

LittlerootTown_MaysHouse_1F_MapBlockdata::
	.incbin "data/maps/LittlerootTown_MaysHouse_1F/map.bin"

	.align 2
LittlerootTown_MaysHouse_1F_MapAttributes::
	.4byte 0xb
	.4byte 0x9
	.4byte LittlerootTown_MaysHouse_1F_MapBorder
	.4byte LittlerootTown_MaysHouse_1F_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_BrendansMaysHouse

LittlerootTown_MaysHouse_2F_MapBorder::
	.incbin "data/maps/LittlerootTown_MaysHouse_2F/border.bin"

LittlerootTown_MaysHouse_2F_MapBlockdata::
	.incbin "data/maps/LittlerootTown_MaysHouse_2F/map.bin"

	.align 2
LittlerootTown_MaysHouse_2F_MapAttributes::
	.4byte 0x9
	.4byte 0x8
	.4byte LittlerootTown_MaysHouse_2F_MapBorder
	.4byte LittlerootTown_MaysHouse_2F_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_BrendansMaysHouse

LittlerootTown_ProfessorBirchsLab_MapBorder::
	.incbin "data/maps/LittlerootTown_ProfessorBirchsLab/border.bin"

LittlerootTown_ProfessorBirchsLab_MapBlockdata::
	.incbin "data/maps/LittlerootTown_ProfessorBirchsLab/map.bin"

	.align 2
LittlerootTown_ProfessorBirchsLab_MapAttributes::
	.4byte 0xd
	.4byte 0xd
	.4byte LittlerootTown_ProfessorBirchsLab_MapBorder
	.4byte LittlerootTown_ProfessorBirchsLab_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_Lab

House1_MapBorder::
	.incbin "data/maps/House1/border.bin"

House1_MapBlockdata::
	.incbin "data/maps/House1/map.bin"

	.align 2
House1_MapAttributes::
	.4byte 0xa
	.4byte 0x9
	.4byte House1_MapBorder
	.4byte House1_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_GenericBuilding

House2_MapBorder::
	.incbin "data/maps/House2/border.bin"

House2_MapBlockdata::
	.incbin "data/maps/House2/map.bin"

	.align 2
House2_MapAttributes::
	.4byte 0xb
	.4byte 0x8
	.4byte House2_MapBorder
	.4byte House2_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_GenericBuilding

PokemonCenter_1F_MapBorder::
	.incbin "data/maps/OldaleTown_PokemonCenter_1F/border.bin"

PokemonCenter_1F_MapBlockdata::
	.incbin "data/maps/OldaleTown_PokemonCenter_1F/map.bin"

	.align 2
PokemonCenter_1F_MapAttributes::
	.4byte 0xe
	.4byte 0x9
	.4byte PokemonCenter_1F_MapBorder
	.4byte PokemonCenter_1F_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_PokemonCenter

PokemonCenter_2F_MapBorder::
	.incbin "data/maps/OldaleTown_PokemonCenter_2F/border.bin"

PokemonCenter_2F_MapBlockdata::
	.incbin "data/maps/OldaleTown_PokemonCenter_2F/map.bin"

	.align 2
PokemonCenter_2F_MapAttributes::
	.4byte 0xe
	.4byte 0x9
	.4byte PokemonCenter_2F_MapBorder
	.4byte PokemonCenter_2F_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_PokemonCenter

PokeMart_MapBorder::
	.incbin "data/maps/OldaleTown_Mart/border.bin"

PokeMart_MapBlockdata::
	.incbin "data/maps/OldaleTown_Mart/map.bin"

	.align 2
PokeMart_MapAttributes::
	.4byte 0xb
	.4byte 0x8
	.4byte PokeMart_MapBorder
	.4byte PokeMart_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_Shop

DewfordTown_House1_MapBorder::
	.incbin "data/maps/DewfordTown_House1/border.bin"

DewfordTown_House1_MapBlockdata::
	.incbin "data/maps/DewfordTown_House1/map.bin"

	.align 2
DewfordTown_House1_MapAttributes::
LavaridgeTown_House_MapAttributes::
Route111_OldLadysRestStop_MapAttributes::
	.4byte 0xa
	.4byte 0x8
	.4byte DewfordTown_House1_MapBorder
	.4byte DewfordTown_House1_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_GenericBuilding

DewfordTown_Gym_MapBorder::
	.incbin "data/maps/DewfordTown_Gym/border.bin"

DewfordTown_Gym_MapBlockdata::
	.incbin "data/maps/DewfordTown_Gym/map.bin"

	.align 2
DewfordTown_Gym_MapAttributes::
	.4byte 0x12
	.4byte 0x1c
	.4byte DewfordTown_Gym_MapBorder
	.4byte DewfordTown_Gym_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_DewfordGym

DewfordTown_Hall_MapBorder::
	.incbin "data/maps/DewfordTown_Hall/border.bin"

DewfordTown_Hall_MapBlockdata::
	.incbin "data/maps/DewfordTown_Hall/map.bin"

	.align 2
DewfordTown_Hall_MapAttributes::
	.4byte 0x11
	.4byte 0x9
	.4byte DewfordTown_Hall_MapBorder
	.4byte DewfordTown_Hall_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_GenericBuilding

DewfordTown_House2_MapBorder::
	.incbin "data/maps/DewfordTown_House2/border.bin"

DewfordTown_House2_MapBlockdata::
	.incbin "data/maps/DewfordTown_House2/map.bin"

	.align 2
DewfordTown_House2_MapAttributes::
Route113_GlassWorkshop_MapAttributes::
	.4byte 0xa
	.4byte 0x9
	.4byte DewfordTown_House2_MapBorder
	.4byte DewfordTown_House2_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_GenericBuilding

LavaridgeTown_HerbShop_MapBorder::
	.incbin "data/maps/LavaridgeTown_HerbShop/border.bin"

LavaridgeTown_HerbShop_MapBlockdata::
	.incbin "data/maps/LavaridgeTown_HerbShop/map.bin"

	.align 2
LavaridgeTown_HerbShop_MapAttributes::
	.4byte 0xb
	.4byte 0x8
	.4byte LavaridgeTown_HerbShop_MapBorder
	.4byte LavaridgeTown_HerbShop_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_Shop

LavaridgeTown_Gym_1F_MapBorder::
	.incbin "data/maps/LavaridgeTown_Gym_1F/border.bin"

LavaridgeTown_Gym_1F_MapBlockdata::
	.incbin "data/maps/LavaridgeTown_Gym_1F/map.bin"

	.align 2
LavaridgeTown_Gym_1F_MapAttributes::
	.4byte 0xb
	.4byte 0x18
	.4byte LavaridgeTown_Gym_1F_MapBorder
	.4byte LavaridgeTown_Gym_1F_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_LavaridgeGym

LavaridgeTown_Gym_B1F_MapBorder::
	.incbin "data/maps/LavaridgeTown_Gym_B1F/border.bin"

LavaridgeTown_Gym_B1F_MapBlockdata::
	.incbin "data/maps/LavaridgeTown_Gym_B1F/map.bin"

	.align 2
LavaridgeTown_Gym_B1F_MapAttributes::
	.4byte 0xb
	.4byte 0x18
	.4byte LavaridgeTown_Gym_B1F_MapBorder
	.4byte LavaridgeTown_Gym_B1F_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_LavaridgeGym

LavaridgeTown_PokemonCenter_1F_MapBorder::
	.incbin "data/maps/LavaridgeTown_PokemonCenter_1F/border.bin"

LavaridgeTown_PokemonCenter_1F_MapBlockdata::
	.incbin "data/maps/LavaridgeTown_PokemonCenter_1F/map.bin"

	.align 2
LavaridgeTown_PokemonCenter_1F_MapAttributes::
	.4byte 0xe
	.4byte 0x9
	.4byte LavaridgeTown_PokemonCenter_1F_MapBorder
	.4byte LavaridgeTown_PokemonCenter_1F_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_PokemonCenter

FallarborTown_ContestLobby_MapBorder::
	.incbin "data/maps/FallarborTown_ContestLobby/border.bin"

FallarborTown_ContestLobby_MapBlockdata::
	.incbin "data/maps/FallarborTown_ContestLobby/map.bin"

	.align 2
FallarborTown_ContestLobby_MapAttributes::
SlateportCity_ContestLobby_MapAttributes::
VerdanturfTown_ContestLobby_MapAttributes::
	.4byte 0xf
	.4byte 0x7
	.4byte FallarborTown_ContestLobby_MapBorder
	.4byte FallarborTown_ContestLobby_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_Contest

FallarborTown_ContestHall_MapBorder::
	.incbin "data/maps/FallarborTown_ContestHall/border.bin"

FallarborTown_ContestHall_MapBlockdata::
	.incbin "data/maps/FallarborTown_ContestHall/map.bin"

	.align 2
FallarborTown_ContestHall_MapAttributes::
SlateportCity_ContestHall_MapAttributes::
VerdanturfTown_ContestHall_MapAttributes::
	.4byte 0x15
	.4byte 0x12
	.4byte FallarborTown_ContestHall_MapBorder
	.4byte FallarborTown_ContestHall_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_Contest

LilycoveCity_House2_MapBorder::
	.incbin "data/maps/LilycoveCity_House2/border.bin"

LilycoveCity_House2_MapBlockdata::
	.incbin "data/maps/LilycoveCity_House2/map.bin"

	.align 2
LilycoveCity_House2_MapAttributes::
	.4byte 0x8
	.4byte 0x8
	.4byte LilycoveCity_House2_MapBorder
	.4byte LilycoveCity_House2_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_GenericBuilding

UnknownMapBorder_082CF564::
	.incbin "data/maps/UnknownMap_082CF564/border.bin"

UnknownMapBlockdata_082CF564::
	.incbin "data/maps/UnknownMap_082CF564/map.bin"

	.align 2
UnknownMapAttributes_082CF564::
	.4byte 0x1
	.4byte 0x1
	.4byte UnknownMapBorder_082CF564
	.4byte UnknownMapBlockdata_082CF564
	.4byte gTileset_Building
	.4byte gTileset_Contest

VerdanturfTown_WandasHouse_MapBorder::
	.incbin "data/maps/VerdanturfTown_WandasHouse/border.bin"

VerdanturfTown_WandasHouse_MapBlockdata::
	.incbin "data/maps/VerdanturfTown_WandasHouse/map.bin"

	.align 2
VerdanturfTown_WandasHouse_MapAttributes::
	.4byte 0x11
	.4byte 0x8
	.4byte VerdanturfTown_WandasHouse_MapBorder
	.4byte VerdanturfTown_WandasHouse_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_GenericBuilding

PacifidlogTown_House1_MapBorder::
	.incbin "data/maps/PacifidlogTown_House1/border.bin"

PacifidlogTown_House1_MapBlockdata::
	.incbin "data/maps/PacifidlogTown_House1/map.bin"

	.align 2
PacifidlogTown_House1_MapAttributes::
PacifidlogTown_House3_MapAttributes::
PacifidlogTown_House5_MapAttributes::
	.4byte 0xa
	.4byte 0x9
	.4byte PacifidlogTown_House1_MapBorder
	.4byte PacifidlogTown_House1_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_GenericBuilding

PacifidlogTown_House2_MapBorder::
	.incbin "data/maps/PacifidlogTown_House2/border.bin"

PacifidlogTown_House2_MapBlockdata::
	.incbin "data/maps/PacifidlogTown_House2/map.bin"

	.align 2
PacifidlogTown_House2_MapAttributes::
PacifidlogTown_House4_MapAttributes::
	.4byte 0xa
	.4byte 0x9
	.4byte PacifidlogTown_House2_MapBorder
	.4byte PacifidlogTown_House2_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_GenericBuilding

PetalburgCity_Gym_MapBorder::
	.incbin "data/maps/PetalburgCity_Gym/border.bin"

PetalburgCity_Gym_MapBlockdata::
	.incbin "data/maps/PetalburgCity_Gym/map.bin"

	.align 2
PetalburgCity_Gym_MapAttributes::
	.4byte 0x9
	.4byte 0x70
	.4byte PetalburgCity_Gym_MapBorder
	.4byte PetalburgCity_Gym_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_PetalburgGym

PetalburgCity_House2_MapBorder::
	.incbin "data/maps/PetalburgCity_House2/border.bin"

PetalburgCity_House2_MapBlockdata::
	.incbin "data/maps/PetalburgCity_House2/map.bin"

	.align 2
MossdeepCity_House4_MapAttributes::
PetalburgCity_House2_MapAttributes::
SlateportCity_House1_MapAttributes::
	.4byte 0xa
	.4byte 0x8
	.4byte PetalburgCity_House2_MapBorder
	.4byte PetalburgCity_House2_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_GenericBuilding

SlateportCity_SternsShipyard_1F_MapBorder::
	.incbin "data/maps/SlateportCity_SternsShipyard_1F/border.bin"

SlateportCity_SternsShipyard_1F_MapBlockdata::
	.incbin "data/maps/SlateportCity_SternsShipyard_1F/map.bin"

	.align 2
SlateportCity_SternsShipyard_1F_MapAttributes::
	.4byte 0x15
	.4byte 0xf
	.4byte SlateportCity_SternsShipyard_1F_MapBorder
	.4byte SlateportCity_SternsShipyard_1F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Facility

SlateportCity_SternsShipyard_2F_MapBorder::
	.incbin "data/maps/SlateportCity_SternsShipyard_2F/border.bin"

SlateportCity_SternsShipyard_2F_MapBlockdata::
	.incbin "data/maps/SlateportCity_SternsShipyard_2F/map.bin"

	.align 2
SlateportCity_SternsShipyard_2F_MapAttributes::
	.4byte 0x11
	.4byte 0xf
	.4byte SlateportCity_SternsShipyard_2F_MapBorder
	.4byte SlateportCity_SternsShipyard_2F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Facility

UnknownMapBorder_082D05D8::
	.incbin "data/maps/UnknownMap_082D05D8/border.bin"

UnknownMapBlockdata_082D05D8::
	.incbin "data/maps/UnknownMap_082D05D8/map.bin"

	.align 2
UnknownMapAttributes_082D05D8::
	.4byte 0x1
	.4byte 0x1
	.4byte UnknownMapBorder_082D05D8
	.4byte UnknownMapBlockdata_082D05D8
	.4byte gTileset_Building
	.4byte gTileset_Contest

UnknownMapBorder_082D05FC::
	.incbin "data/maps/UnknownMap_082D05FC/border.bin"

UnknownMapBlockdata_082D05FC::
	.incbin "data/maps/UnknownMap_082D05FC/map.bin"

	.align 2
UnknownMapAttributes_082D05FC::
	.4byte 0x1
	.4byte 0x1
	.4byte UnknownMapBorder_082D05FC
	.4byte UnknownMapBlockdata_082D05FC
	.4byte gTileset_Building
	.4byte gTileset_Contest

SlateportCity_PokemonFanClub_MapBorder::
	.incbin "data/maps/SlateportCity_PokemonFanClub/border.bin"

SlateportCity_PokemonFanClub_MapBlockdata::
	.incbin "data/maps/SlateportCity_PokemonFanClub/map.bin"

	.align 2
SlateportCity_PokemonFanClub_MapAttributes::
	.4byte 0xe
	.4byte 0xb
	.4byte SlateportCity_PokemonFanClub_MapBorder
	.4byte SlateportCity_PokemonFanClub_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_PokemonFanClub

SlateportCity_OceanicMuseum_1F_MapBorder::
	.incbin "data/maps/SlateportCity_OceanicMuseum_1F/border.bin"

SlateportCity_OceanicMuseum_1F_MapBlockdata::
	.incbin "data/maps/SlateportCity_OceanicMuseum_1F/map.bin"

	.align 2
SlateportCity_OceanicMuseum_1F_MapAttributes::
	.4byte 0x14
	.4byte 0x9
	.4byte SlateportCity_OceanicMuseum_1F_MapBorder
	.4byte SlateportCity_OceanicMuseum_1F_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_OceanicMuseum

SlateportCity_OceanicMuseum_2F_MapBorder::
	.incbin "data/maps/SlateportCity_OceanicMuseum_2F/border.bin"

SlateportCity_OceanicMuseum_2F_MapBlockdata::
	.incbin "data/maps/SlateportCity_OceanicMuseum_2F/map.bin"

	.align 2
SlateportCity_OceanicMuseum_2F_MapAttributes::
	.4byte 0x14
	.4byte 0x9
	.4byte SlateportCity_OceanicMuseum_2F_MapBorder
	.4byte SlateportCity_OceanicMuseum_2F_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_OceanicMuseum

SlateportCity_Harbor_MapBorder::
	.incbin "data/maps/SlateportCity_Harbor/border.bin"

SlateportCity_Harbor_MapBlockdata::
	.incbin "data/maps/SlateportCity_Harbor/map.bin"

	.align 2
LilycoveCity_Harbor_MapAttributes::
SlateportCity_Harbor_MapAttributes::
	.4byte 0x18
	.4byte 0xf
	.4byte SlateportCity_Harbor_MapBorder
	.4byte SlateportCity_Harbor_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Facility

MauvilleCity_Gym_MapBorder::
	.incbin "data/maps/MauvilleCity_Gym/border.bin"

MauvilleCity_Gym_MapBlockdata::
	.incbin "data/maps/MauvilleCity_Gym/map.bin"

	.align 2
MauvilleCity_Gym_MapAttributes::
	.4byte 0xa
	.4byte 0x15
	.4byte MauvilleCity_Gym_MapBorder
	.4byte MauvilleCity_Gym_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_MauvilleGym

MauvilleCity_BikeShop_MapBorder::
	.incbin "data/maps/MauvilleCity_BikeShop/border.bin"

MauvilleCity_BikeShop_MapBlockdata::
	.incbin "data/maps/MauvilleCity_BikeShop/map.bin"

	.align 2
MauvilleCity_BikeShop_MapAttributes::
	.4byte 0xc
	.4byte 0x9
	.4byte MauvilleCity_BikeShop_MapBorder
	.4byte MauvilleCity_BikeShop_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_BikeShop

MauvilleCity_GameCorner_MapBorder::
	.incbin "data/maps/MauvilleCity_GameCorner/border.bin"

MauvilleCity_GameCorner_MapBlockdata::
	.incbin "data/maps/MauvilleCity_GameCorner/map.bin"

	.align 2
MauvilleCity_GameCorner_MapAttributes::
	.4byte 0x16
	.4byte 0xb
	.4byte MauvilleCity_GameCorner_MapBorder
	.4byte MauvilleCity_GameCorner_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_MauvilleGameCorner

RustboroCity_DevonCorp_1F_MapBorder::
	.incbin "data/maps/RustboroCity_DevonCorp_1F/border.bin"

RustboroCity_DevonCorp_1F_MapBlockdata::
	.incbin "data/maps/RustboroCity_DevonCorp_1F/map.bin"

	.align 2
RustboroCity_DevonCorp_1F_MapAttributes::
	.4byte 0x13
	.4byte 0x9
	.4byte RustboroCity_DevonCorp_1F_MapBorder
	.4byte RustboroCity_DevonCorp_1F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Facility

RustboroCity_DevonCorp_2F_MapBorder::
	.incbin "data/maps/RustboroCity_DevonCorp_2F/border.bin"

RustboroCity_DevonCorp_2F_MapBlockdata::
	.incbin "data/maps/RustboroCity_DevonCorp_2F/map.bin"

	.align 2
RustboroCity_DevonCorp_2F_MapAttributes::
	.4byte 0x13
	.4byte 0x9
	.4byte RustboroCity_DevonCorp_2F_MapBorder
	.4byte RustboroCity_DevonCorp_2F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Facility

RustboroCity_Gym_MapBorder::
	.incbin "data/maps/RustboroCity_Gym/border.bin"

RustboroCity_Gym_MapBlockdata::
	.incbin "data/maps/RustboroCity_Gym/map.bin"

	.align 2
RustboroCity_Gym_MapAttributes::
	.4byte 0xb
	.4byte 0x13
	.4byte RustboroCity_Gym_MapBorder
	.4byte RustboroCity_Gym_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_RustboroGym

RustboroCity_PokemonSchool_MapBorder::
	.incbin "data/maps/RustboroCity_PokemonSchool/border.bin"

RustboroCity_PokemonSchool_MapBlockdata::
	.incbin "data/maps/RustboroCity_PokemonSchool/map.bin"

	.align 2
RustboroCity_PokemonSchool_MapAttributes::
	.4byte 0xc
	.4byte 0xb
	.4byte RustboroCity_PokemonSchool_MapBorder
	.4byte RustboroCity_PokemonSchool_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_PokemonSchool

RustboroCity_House2_MapBorder::
	.incbin "data/maps/RustboroCity_House2/border.bin"

RustboroCity_House2_MapBlockdata::
	.incbin "data/maps/RustboroCity_House2/map.bin"

	.align 2
RustboroCity_House2_MapAttributes::
RustboroCity_House3_MapAttributes::
	.4byte 0xc
	.4byte 0x9
	.4byte RustboroCity_House2_MapBorder
	.4byte RustboroCity_House2_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_GenericBuilding

RustboroCity_House1_MapBorder::
	.incbin "data/maps/RustboroCity_House1/border.bin"

RustboroCity_House1_MapBlockdata::
	.incbin "data/maps/RustboroCity_House1/map.bin"

	.align 2
RustboroCity_House1_MapAttributes::
	.4byte 0xd
	.4byte 0x8
	.4byte RustboroCity_House1_MapBorder
	.4byte RustboroCity_House1_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_GenericBuilding

RustboroCity_CuttersHouse_MapBorder::
	.incbin "data/maps/RustboroCity_CuttersHouse/border.bin"

RustboroCity_CuttersHouse_MapBlockdata::
	.incbin "data/maps/RustboroCity_CuttersHouse/map.bin"

	.align 2
RustboroCity_CuttersHouse_MapAttributes::
	.4byte 0xb
	.4byte 0x9
	.4byte RustboroCity_CuttersHouse_MapBorder
	.4byte RustboroCity_CuttersHouse_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_GenericBuilding

FortreeCity_House1_MapBorder::
	.incbin "data/maps/FortreeCity_House1/border.bin"

FortreeCity_House1_MapBlockdata::
	.incbin "data/maps/FortreeCity_House1/map.bin"

	.align 2
FortreeCity_House1_MapAttributes::
FortreeCity_House3_MapAttributes::
FortreeCity_House5_MapAttributes::
	.4byte 0x8
	.4byte 0x6
	.4byte FortreeCity_House1_MapBorder
	.4byte FortreeCity_House1_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_GenericBuilding

FortreeCity_Gym_MapBorder::
	.incbin "data/maps/FortreeCity_Gym/border.bin"

FortreeCity_Gym_MapBlockdata::
	.incbin "data/maps/FortreeCity_Gym/map.bin"

	.align 2
FortreeCity_Gym_MapAttributes::
	.4byte 0x14
	.4byte 0x19
	.4byte FortreeCity_Gym_MapBorder
	.4byte FortreeCity_Gym_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_FortreeGym

FortreeCity_House2_MapBorder::
	.incbin "data/maps/FortreeCity_House2/border.bin"

FortreeCity_House2_MapBlockdata::
	.incbin "data/maps/FortreeCity_House2/map.bin"

	.align 2
FortreeCity_House2_MapAttributes::
FortreeCity_House4_MapAttributes::
	.4byte 0x8
	.4byte 0x6
	.4byte FortreeCity_House2_MapBorder
	.4byte FortreeCity_House2_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_GenericBuilding

Route104_MrBrineysHouse_MapBorder::
	.incbin "data/maps/Route104_MrBrineysHouse/border.bin"

Route104_MrBrineysHouse_MapBlockdata::
	.incbin "data/maps/Route104_MrBrineysHouse/map.bin"

	.align 2
Route104_MrBrineysHouse_MapAttributes::
	.4byte 0xc
	.4byte 0x9
	.4byte Route104_MrBrineysHouse_MapBorder
	.4byte Route104_MrBrineysHouse_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_GenericBuilding

LilycoveCity_LilycoveMuseum_1F_MapBorder::
	.incbin "data/maps/LilycoveCity_LilycoveMuseum_1F/border.bin"

LilycoveCity_LilycoveMuseum_1F_MapBlockdata::
	.incbin "data/maps/LilycoveCity_LilycoveMuseum_1F/map.bin"

	.align 2
LilycoveCity_LilycoveMuseum_1F_MapAttributes::
	.4byte 0x15
	.4byte 0xe
	.4byte LilycoveCity_LilycoveMuseum_1F_MapBorder
	.4byte LilycoveCity_LilycoveMuseum_1F_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_LilycoveMuseum

LilycoveCity_LilycoveMuseum_2F_MapBorder::
	.incbin "data/maps/LilycoveCity_LilycoveMuseum_2F/border.bin"

LilycoveCity_LilycoveMuseum_2F_MapBlockdata::
	.incbin "data/maps/LilycoveCity_LilycoveMuseum_2F/map.bin"

	.align 2
LilycoveCity_LilycoveMuseum_2F_MapAttributes::
	.4byte 0x16
	.4byte 0xd
	.4byte LilycoveCity_LilycoveMuseum_2F_MapBorder
	.4byte LilycoveCity_LilycoveMuseum_2F_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_LilycoveMuseum

LilycoveCity_ContestLobby_MapBorder::
	.incbin "data/maps/LilycoveCity_ContestLobby/border.bin"

LilycoveCity_ContestLobby_MapBlockdata::
	.incbin "data/maps/LilycoveCity_ContestLobby/map.bin"

	.align 2
LilycoveCity_ContestLobby_MapAttributes::
	.4byte 0x17
	.4byte 0xc
	.4byte LilycoveCity_ContestLobby_MapBorder
	.4byte LilycoveCity_ContestLobby_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_Contest

LilycoveCity_ContestHall_MapBorder::
	.incbin "data/maps/LilycoveCity_ContestHall/border.bin"

LilycoveCity_ContestHall_MapBlockdata::
	.incbin "data/maps/LilycoveCity_ContestHall/map.bin"

	.align 2
LilycoveCity_ContestHall_MapAttributes::
	.4byte 0x33
	.4byte 0x21
	.4byte LilycoveCity_ContestHall_MapBorder
	.4byte LilycoveCity_ContestHall_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_Contest

LilycoveCity_PokemonTrainerFanClub_MapBorder::
	.incbin "data/maps/LilycoveCity_PokemonTrainerFanClub/border.bin"

LilycoveCity_PokemonTrainerFanClub_MapBlockdata::
	.incbin "data/maps/LilycoveCity_PokemonTrainerFanClub/map.bin"

	.align 2
LilycoveCity_PokemonTrainerFanClub_MapAttributes::
	.4byte 0xc
	.4byte 0xe
	.4byte LilycoveCity_PokemonTrainerFanClub_MapBorder
	.4byte LilycoveCity_PokemonTrainerFanClub_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_GenericBuilding

LilycoveCity_EmptyMap_MapBorder::
	.incbin "data/maps/LilycoveCity_EmptyMap/border.bin"

LilycoveCity_EmptyMap_MapBlockdata::
	.incbin "data/maps/LilycoveCity_EmptyMap/map.bin"

	.align 2
LilycoveCity_EmptyMap_MapAttributes::
	.4byte 0x1
	.4byte 0x1
	.4byte LilycoveCity_EmptyMap_MapBorder
	.4byte LilycoveCity_EmptyMap_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Facility

MossdeepCity_Gym_MapBorder::
	.incbin "data/maps/MossdeepCity_Gym/border.bin"

MossdeepCity_Gym_MapBlockdata::
	.incbin "data/maps/MossdeepCity_Gym/map.bin"

	.align 2
MossdeepCity_Gym_MapAttributes::
	.4byte 0x14
	.4byte 0x1e
	.4byte MossdeepCity_Gym_MapBorder
	.4byte MossdeepCity_Gym_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_MossdeepGym

SootopolisCity_Gym_1F_MapBorder::
	.incbin "data/maps/SootopolisCity_Gym_1F/border.bin"

SootopolisCity_Gym_1F_MapBlockdata::
	.incbin "data/maps/SootopolisCity_Gym_1F/map.bin"

	.align 2
SootopolisCity_Gym_1F_MapAttributes::
	.4byte 0x11
	.4byte 0x1a
	.4byte SootopolisCity_Gym_1F_MapBorder
	.4byte SootopolisCity_Gym_1F_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_SootopolisGym

SootopolisCity_Gym_B1F_MapBorder::
	.incbin "data/maps/SootopolisCity_Gym_B1F/border.bin"

SootopolisCity_Gym_B1F_MapBlockdata::
	.incbin "data/maps/SootopolisCity_Gym_B1F/map.bin"

	.align 2
SootopolisCity_Gym_B1F_MapAttributes::
	.4byte 0x11
	.4byte 0x1a
	.4byte SootopolisCity_Gym_B1F_MapBorder
	.4byte SootopolisCity_Gym_B1F_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_SootopolisGym

EverGrandeCity_SidneysRoom_MapBorder::
	.incbin "data/maps/EverGrandeCity_SidneysRoom/border.bin"

EverGrandeCity_SidneysRoom_MapBlockdata::
	.incbin "data/maps/EverGrandeCity_SidneysRoom/map.bin"

	.align 2
EverGrandeCity_SidneysRoom_MapAttributes::
	.4byte 0xd
	.4byte 0xe
	.4byte EverGrandeCity_SidneysRoom_MapBorder
	.4byte EverGrandeCity_SidneysRoom_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_EliteFour

EverGrandeCity_PhoebesRoom_MapBorder::
	.incbin "data/maps/EverGrandeCity_PhoebesRoom/border.bin"

EverGrandeCity_PhoebesRoom_MapBlockdata::
	.incbin "data/maps/EverGrandeCity_PhoebesRoom/map.bin"

	.align 2
EverGrandeCity_PhoebesRoom_MapAttributes::
	.4byte 0xd
	.4byte 0xe
	.4byte EverGrandeCity_PhoebesRoom_MapBorder
	.4byte EverGrandeCity_PhoebesRoom_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_EliteFour

EverGrandeCity_GlaciasRoom_MapBorder::
	.incbin "data/maps/EverGrandeCity_GlaciasRoom/border.bin"

EverGrandeCity_GlaciasRoom_MapBlockdata::
	.incbin "data/maps/EverGrandeCity_GlaciasRoom/map.bin"

	.align 2
EverGrandeCity_GlaciasRoom_MapAttributes::
	.4byte 0xd
	.4byte 0xe
	.4byte EverGrandeCity_GlaciasRoom_MapBorder
	.4byte EverGrandeCity_GlaciasRoom_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_EliteFour

EverGrandeCity_DrakesRoom_MapBorder::
	.incbin "data/maps/EverGrandeCity_DrakesRoom/border.bin"

EverGrandeCity_DrakesRoom_MapBlockdata::
	.incbin "data/maps/EverGrandeCity_DrakesRoom/map.bin"

	.align 2
EverGrandeCity_DrakesRoom_MapAttributes::
	.4byte 0xd
	.4byte 0xe
	.4byte EverGrandeCity_DrakesRoom_MapBorder
	.4byte EverGrandeCity_DrakesRoom_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_EliteFour

EverGrandeCity_ChampionsRoom_MapBorder::
	.incbin "data/maps/EverGrandeCity_ChampionsRoom/border.bin"

EverGrandeCity_ChampionsRoom_MapBlockdata::
	.incbin "data/maps/EverGrandeCity_ChampionsRoom/map.bin"

	.align 2
EverGrandeCity_ChampionsRoom_MapAttributes::
	.4byte 0xd
	.4byte 0xd
	.4byte EverGrandeCity_ChampionsRoom_MapBorder
	.4byte EverGrandeCity_ChampionsRoom_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_EliteFour

EverGrandeCity_Corridor1_MapBorder::
	.incbin "data/maps/EverGrandeCity_Corridor1/border.bin"

EverGrandeCity_Corridor1_MapBlockdata::
	.incbin "data/maps/EverGrandeCity_Corridor1/map.bin"

	.align 2
EverGrandeCity_Corridor1_MapAttributes::
EverGrandeCity_Corridor2_MapAttributes::
EverGrandeCity_Corridor3_MapAttributes::
EverGrandeCity_Corridor5_MapAttributes::
	.4byte 0xb
	.4byte 0xd
	.4byte EverGrandeCity_Corridor1_MapBorder
	.4byte EverGrandeCity_Corridor1_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_EliteFour

Route104_PrettyPetalFlowerShop_MapBorder::
	.incbin "data/maps/Route104_PrettyPetalFlowerShop/border.bin"

Route104_PrettyPetalFlowerShop_MapBlockdata::
	.incbin "data/maps/Route104_PrettyPetalFlowerShop/map.bin"

	.align 2
Route104_PrettyPetalFlowerShop_MapAttributes::
Route104_PrototypePrettyPetalFlowerShop_MapAttributes::
	.4byte 0xf
	.4byte 0x9
	.4byte Route104_PrettyPetalFlowerShop_MapBorder
	.4byte Route104_PrettyPetalFlowerShop_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_PrettyPetalFlowerShop

Route112_CableCarStation_MapBorder::
	.incbin "data/maps/Route112_CableCarStation/border.bin"

Route112_CableCarStation_MapBlockdata::
	.incbin "data/maps/Route112_CableCarStation/map.bin"

	.align 2
MtChimney_CableCarStation_MapAttributes::
Route112_CableCarStation_MapAttributes::
	.4byte 0xd
	.4byte 0xc
	.4byte Route112_CableCarStation_MapBorder
	.4byte Route112_CableCarStation_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Facility

Route114_FossilManiacsHouse_MapBorder::
	.incbin "data/maps/Route114_FossilManiacsHouse/border.bin"

Route114_FossilManiacsHouse_MapBlockdata::
	.incbin "data/maps/Route114_FossilManiacsHouse/map.bin"

	.align 2
Route114_FossilManiacsHouse_MapAttributes::
	.4byte 0xa
	.4byte 0x8
	.4byte Route114_FossilManiacsHouse_MapBorder
	.4byte Route114_FossilManiacsHouse_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_GenericBuilding

Route114_FossilManiacsTunnel_MapBorder::
	.incbin "data/maps/Route114_FossilManiacsTunnel/border.bin"

Route114_FossilManiacsTunnel_MapBlockdata::
	.incbin "data/maps/Route114_FossilManiacsTunnel/map.bin"

	.align 2
Route114_FossilManiacsTunnel_MapAttributes::
	.4byte 0xd
	.4byte 0x1a
	.4byte Route114_FossilManiacsTunnel_MapBorder
	.4byte Route114_FossilManiacsTunnel_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Fallarbor

Route114_LanettesHouse_MapBorder::
	.incbin "data/maps/Route114_LanettesHouse/border.bin"

Route114_LanettesHouse_MapBlockdata::
	.incbin "data/maps/Route114_LanettesHouse/map.bin"

	.align 2
Route114_LanettesHouse_MapAttributes::
	.4byte 0xb
	.4byte 0x8
	.4byte Route114_LanettesHouse_MapBorder
	.4byte Route114_LanettesHouse_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_Lab

Route116_TunnelersRestHouse_MapBorder::
	.incbin "data/maps/Route116_TunnelersRestHouse/border.bin"

Route116_TunnelersRestHouse_MapBlockdata::
	.incbin "data/maps/Route116_TunnelersRestHouse/map.bin"

	.align 2
Route116_TunnelersRestHouse_MapAttributes::
	.4byte 0xa
	.4byte 0x9
	.4byte Route116_TunnelersRestHouse_MapBorder
	.4byte Route116_TunnelersRestHouse_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_GenericBuilding

Route117_PokemonDayCare_MapBorder::
	.incbin "data/maps/Route117_PokemonDayCare/border.bin"

Route117_PokemonDayCare_MapBlockdata::
	.incbin "data/maps/Route117_PokemonDayCare/map.bin"

	.align 2
Route117_PokemonDayCare_MapAttributes::
	.4byte 0xc
	.4byte 0x9
	.4byte Route117_PokemonDayCare_MapBorder
	.4byte Route117_PokemonDayCare_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_PokemonDayCare

Route121_SafariZoneEntrance_MapBorder::
	.incbin "data/maps/Route121_SafariZoneEntrance/border.bin"

Route121_SafariZoneEntrance_MapBlockdata::
	.incbin "data/maps/Route121_SafariZoneEntrance/map.bin"

	.align 2
Route121_SafariZoneEntrance_MapAttributes::
	.4byte 0x12
	.4byte 0xe
	.4byte Route121_SafariZoneEntrance_MapBorder
	.4byte Route121_SafariZoneEntrance_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_Shop

MeteorFalls_1F_1R_MapBorder::
	.incbin "data/maps/MeteorFalls_1F_1R/border.bin"

MeteorFalls_1F_1R_MapBlockdata::
	.incbin "data/maps/MeteorFalls_1F_1R/map.bin"

	.align 2
MeteorFalls_1F_1R_MapAttributes::
	.4byte 0x1e
	.4byte 0x2a
	.4byte MeteorFalls_1F_1R_MapBorder
	.4byte MeteorFalls_1F_1R_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_MeteorFalls

MeteorFalls_1F_2R_MapBorder::
	.incbin "data/maps/MeteorFalls_1F_2R/border.bin"

MeteorFalls_1F_2R_MapBlockdata::
	.incbin "data/maps/MeteorFalls_1F_2R/map.bin"

	.align 2
MeteorFalls_1F_2R_MapAttributes::
	.4byte 0x1e
	.4byte 0x20
	.4byte MeteorFalls_1F_2R_MapBorder
	.4byte MeteorFalls_1F_2R_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_MeteorFalls

MeteorFalls_B1F_1R_MapBorder::
	.incbin "data/maps/MeteorFalls_B1F_1R/border.bin"

MeteorFalls_B1F_1R_MapBlockdata::
	.incbin "data/maps/MeteorFalls_B1F_1R/map.bin"

	.align 2
MeteorFalls_B1F_1R_MapAttributes::
	.4byte 0x1d
	.4byte 0x26
	.4byte MeteorFalls_B1F_1R_MapBorder
	.4byte MeteorFalls_B1F_1R_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_MeteorFalls

MeteorFalls_B1F_2R_MapBorder::
	.incbin "data/maps/MeteorFalls_B1F_2R/border.bin"

MeteorFalls_B1F_2R_MapBlockdata::
	.incbin "data/maps/MeteorFalls_B1F_2R/map.bin"

	.align 2
MeteorFalls_B1F_2R_MapAttributes::
	.4byte 0xb
	.4byte 0x12
	.4byte MeteorFalls_B1F_2R_MapBorder
	.4byte MeteorFalls_B1F_2R_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_MeteorFalls

RusturfTunnel_MapBorder::
	.incbin "data/maps/RusturfTunnel/border.bin"

RusturfTunnel_MapBlockdata::
	.incbin "data/maps/RusturfTunnel/map.bin"

	.align 2
RusturfTunnel_MapAttributes::
	.4byte 0x24
	.4byte 0x18
	.4byte RusturfTunnel_MapBorder
	.4byte RusturfTunnel_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_RusturfTunnel

Underwater_SootopolisCity_MapBorder::
	.incbin "data/maps/Underwater_SootopolisCity/border.bin"

Underwater_SootopolisCity_MapBlockdata::
	.incbin "data/maps/Underwater_SootopolisCity/map.bin"

	.align 2
Underwater_SootopolisCity_MapAttributes::
	.4byte 0x14
	.4byte 0xa
	.4byte Underwater_SootopolisCity_MapBorder
	.4byte Underwater_SootopolisCity_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Underwater

DesertRuins_MapBorder::
	.incbin "data/maps/DesertRuins/border.bin"

DesertRuins_MapBlockdata::
	.incbin "data/maps/DesertRuins/map.bin"

	.align 2
DesertRuins_MapAttributes::
	.4byte 0x11
	.4byte 0x21
	.4byte DesertRuins_MapBorder
	.4byte DesertRuins_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Cave

GraniteCave_1F_MapBorder::
	.incbin "data/maps/GraniteCave_1F/border.bin"

GraniteCave_1F_MapBlockdata::
	.incbin "data/maps/GraniteCave_1F/map.bin"

	.align 2
GraniteCave_1F_MapAttributes::
	.4byte 0x2a
	.4byte 0xf
	.4byte GraniteCave_1F_MapBorder
	.4byte GraniteCave_1F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Cave

GraniteCave_B1F_MapBorder::
	.incbin "data/maps/GraniteCave_B1F/border.bin"

GraniteCave_B1F_MapBlockdata::
	.incbin "data/maps/GraniteCave_B1F/map.bin"

	.align 2
GraniteCave_B1F_MapAttributes::
	.4byte 0x20
	.4byte 0x1a
	.4byte GraniteCave_B1F_MapBorder
	.4byte GraniteCave_B1F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Cave

GraniteCave_B2F_MapBorder::
	.incbin "data/maps/GraniteCave_B2F/border.bin"

GraniteCave_B2F_MapBlockdata::
	.incbin "data/maps/GraniteCave_B2F/map.bin"

	.align 2
GraniteCave_B2F_MapAttributes::
	.4byte 0x20
	.4byte 0x1a
	.4byte GraniteCave_B2F_MapBorder
	.4byte GraniteCave_B2F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Cave

PetalburgWoods_MapBorder::
	.incbin "data/maps/PetalburgWoods/border.bin"

PetalburgWoods_MapBlockdata::
	.incbin "data/maps/PetalburgWoods/map.bin"

	.align 2
PetalburgWoods_MapAttributes::
	.4byte 0x30
	.4byte 0x2c
	.4byte PetalburgWoods_MapBorder
	.4byte PetalburgWoods_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Rustboro

MtChimney_MapBorder::
	.incbin "data/maps/MtChimney/border.bin"

MtChimney_MapBlockdata::
	.incbin "data/maps/MtChimney/map.bin"

	.align 2
MtChimney_MapAttributes::
	.4byte 0x28
	.4byte 0x2f
	.4byte MtChimney_MapBorder
	.4byte MtChimney_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Lavaridge

MtPyre_1F_MapBorder::
	.incbin "data/maps/MtPyre_1F/border.bin"

MtPyre_1F_MapBlockdata::
	.incbin "data/maps/MtPyre_1F/map.bin"

	.align 2
MtPyre_1F_MapAttributes::
	.4byte 0x16
	.4byte 0x13
	.4byte MtPyre_1F_MapBorder
	.4byte MtPyre_1F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Facility

MtPyre_2F_MapBorder::
	.incbin "data/maps/MtPyre_2F/border.bin"

MtPyre_2F_MapBlockdata::
	.incbin "data/maps/MtPyre_2F/map.bin"

	.align 2
MtPyre_2F_MapAttributes::
	.4byte 0xd
	.4byte 0xd
	.4byte MtPyre_2F_MapBorder
	.4byte MtPyre_2F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Facility

MtPyre_3F_MapBorder::
	.incbin "data/maps/MtPyre_3F/border.bin"

MtPyre_3F_MapBlockdata::
	.incbin "data/maps/MtPyre_3F/map.bin"

	.align 2
MtPyre_3F_MapAttributes::
	.4byte 0xd
	.4byte 0xd
	.4byte MtPyre_3F_MapBorder
	.4byte MtPyre_3F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Facility

MtPyre_4F_MapBorder::
	.incbin "data/maps/MtPyre_4F/border.bin"

MtPyre_4F_MapBlockdata::
	.incbin "data/maps/MtPyre_4F/map.bin"

	.align 2
MtPyre_4F_MapAttributes::
	.4byte 0xd
	.4byte 0xd
	.4byte MtPyre_4F_MapBorder
	.4byte MtPyre_4F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Facility

MtPyre_5F_MapBorder::
	.incbin "data/maps/MtPyre_5F/border.bin"

MtPyre_5F_MapBlockdata::
	.incbin "data/maps/MtPyre_5F/map.bin"

	.align 2
MtPyre_5F_MapAttributes::
	.4byte 0xd
	.4byte 0xd
	.4byte MtPyre_5F_MapBorder
	.4byte MtPyre_5F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Facility

MtPyre_6F_MapBorder::
	.incbin "data/maps/MtPyre_6F/border.bin"

MtPyre_6F_MapBlockdata::
	.incbin "data/maps/MtPyre_6F/map.bin"

	.align 2
MtPyre_6F_MapAttributes::
	.4byte 0xd
	.4byte 0xd
	.4byte MtPyre_6F_MapBorder
	.4byte MtPyre_6F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Facility

AquaHideout_1F_MapBorder::
	.incbin "data/maps/AquaHideout_1F/border.bin"

AquaHideout_1F_MapBlockdata::
	.incbin "data/maps/AquaHideout_1F/map.bin"

	.align 2
AquaHideout_1F_MapAttributes::
	.4byte 0x1c
	.4byte 0x1e
	.4byte AquaHideout_1F_MapBorder
	.4byte AquaHideout_1F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Facility

AquaHideout_B1F_MapBorder::
	.incbin "data/maps/AquaHideout_B1F/border.bin"

AquaHideout_B1F_MapBlockdata::
	.incbin "data/maps/AquaHideout_B1F/map.bin"

	.align 2
AquaHideout_B1F_MapAttributes::
	.4byte 0x33
	.4byte 0x18
	.4byte AquaHideout_B1F_MapBorder
	.4byte AquaHideout_B1F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Facility

AquaHideout_B2F_MapBorder::
	.incbin "data/maps/AquaHideout_B2F/border.bin"

AquaHideout_B2F_MapBlockdata::
	.incbin "data/maps/AquaHideout_B2F/map.bin"

	.align 2
AquaHideout_B2F_MapAttributes::
	.4byte 0x22
	.4byte 0x18
	.4byte AquaHideout_B2F_MapBorder
	.4byte AquaHideout_B2F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Facility

Underwater_SeafloorCavern_MapBorder::
	.incbin "data/maps/Underwater_SeafloorCavern/border.bin"

Underwater_SeafloorCavern_MapBlockdata::
	.incbin "data/maps/Underwater_SeafloorCavern/map.bin"

	.align 2
Underwater_SeafloorCavern_MapAttributes::
	.4byte 0xe
	.4byte 0x9
	.4byte Underwater_SeafloorCavern_MapBorder
	.4byte Underwater_SeafloorCavern_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Underwater

SeafloorCavern_Entrance_MapBorder::
	.incbin "data/maps/SeafloorCavern_Entrance/border.bin"

SeafloorCavern_Entrance_MapBlockdata::
	.incbin "data/maps/SeafloorCavern_Entrance/map.bin"

	.align 2
SeafloorCavern_Entrance_MapAttributes::
	.4byte 0x14
	.4byte 0x14
	.4byte SeafloorCavern_Entrance_MapBorder
	.4byte SeafloorCavern_Entrance_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Cave

SeafloorCavern_Room1_MapBorder::
	.incbin "data/maps/SeafloorCavern_Room1/border.bin"

SeafloorCavern_Room1_MapBlockdata::
	.incbin "data/maps/SeafloorCavern_Room1/map.bin"

	.align 2
SeafloorCavern_Room1_MapAttributes::
	.4byte 0x14
	.4byte 0x15
	.4byte SeafloorCavern_Room1_MapBorder
	.4byte SeafloorCavern_Room1_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Cave

SeafloorCavern_Room2_MapBorder::
	.incbin "data/maps/SeafloorCavern_Room2/border.bin"

SeafloorCavern_Room2_MapBlockdata::
	.incbin "data/maps/SeafloorCavern_Room2/map.bin"

	.align 2
SeafloorCavern_Room2_MapAttributes::
	.4byte 0x12
	.4byte 0x15
	.4byte SeafloorCavern_Room2_MapBorder
	.4byte SeafloorCavern_Room2_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Cave

SeafloorCavern_Room3_MapBorder::
	.incbin "data/maps/SeafloorCavern_Room3/border.bin"

SeafloorCavern_Room3_MapBlockdata::
	.incbin "data/maps/SeafloorCavern_Room3/map.bin"

	.align 2
SeafloorCavern_Room3_MapAttributes::
	.4byte 0x10
	.4byte 0x11
	.4byte SeafloorCavern_Room3_MapBorder
	.4byte SeafloorCavern_Room3_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Cave

SeafloorCavern_Room4_MapBorder::
	.incbin "data/maps/SeafloorCavern_Room4/border.bin"

SeafloorCavern_Room4_MapBlockdata::
	.incbin "data/maps/SeafloorCavern_Room4/map.bin"

	.align 2
SeafloorCavern_Room4_MapAttributes::
	.4byte 0x12
	.4byte 0x13
	.4byte SeafloorCavern_Room4_MapBorder
	.4byte SeafloorCavern_Room4_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Cave

SeafloorCavern_Room5_MapBorder::
	.incbin "data/maps/SeafloorCavern_Room5/border.bin"

SeafloorCavern_Room5_MapBlockdata::
	.incbin "data/maps/SeafloorCavern_Room5/map.bin"

	.align 2
SeafloorCavern_Room5_MapAttributes::
	.4byte 0x14
	.4byte 0x14
	.4byte SeafloorCavern_Room5_MapBorder
	.4byte SeafloorCavern_Room5_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Cave

SeafloorCavern_Room6_MapBorder::
	.incbin "data/maps/SeafloorCavern_Room6/border.bin"

SeafloorCavern_Room6_MapBlockdata::
	.incbin "data/maps/SeafloorCavern_Room6/map.bin"

	.align 2
SeafloorCavern_Room6_MapAttributes::
	.4byte 0x18
	.4byte 0x17
	.4byte SeafloorCavern_Room6_MapBorder
	.4byte SeafloorCavern_Room6_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Pacifidlog

SeafloorCavern_Room7_MapBorder::
	.incbin "data/maps/SeafloorCavern_Room7/border.bin"

SeafloorCavern_Room7_MapBlockdata::
	.incbin "data/maps/SeafloorCavern_Room7/map.bin"

	.align 2
SeafloorCavern_Room7_MapAttributes::
	.4byte 0x17
	.4byte 0x19
	.4byte SeafloorCavern_Room7_MapBorder
	.4byte SeafloorCavern_Room7_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Pacifidlog

SeafloorCavern_Room8_MapBorder::
	.incbin "data/maps/SeafloorCavern_Room8/border.bin"

SeafloorCavern_Room8_MapBlockdata::
	.incbin "data/maps/SeafloorCavern_Room8/map.bin"

	.align 2
SeafloorCavern_Room8_MapAttributes::
	.4byte 0xb
	.4byte 0xe
	.4byte SeafloorCavern_Room8_MapBorder
	.4byte SeafloorCavern_Room8_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Cave

SeafloorCavern_Room9_MapBorder::
	.incbin "data/maps/SeafloorCavern_Room9/border.bin"

SeafloorCavern_Room9_MapBlockdata::
	.incbin "data/maps/SeafloorCavern_Room9/map.bin"

	.align 2
SeafloorCavern_Room9_MapAttributes::
	.4byte 0x1b
	.4byte 0x2e
	.4byte SeafloorCavern_Room9_MapBorder
	.4byte SeafloorCavern_Room9_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Cave

CaveOfOrigin_Entrance_MapBorder::
	.incbin "data/maps/CaveOfOrigin_Entrance/border.bin"

CaveOfOrigin_Entrance_MapBlockdata::
	.incbin "data/maps/CaveOfOrigin_Entrance/map.bin"

	.align 2
CaveOfOrigin_Entrance_MapAttributes::
	.4byte 0x13
	.4byte 0x1a
	.4byte CaveOfOrigin_Entrance_MapBorder
	.4byte CaveOfOrigin_Entrance_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Cave

CaveOfOrigin_1F_MapBorder::
	.incbin "data/maps/CaveOfOrigin_1F/border.bin"

CaveOfOrigin_1F_MapBlockdata::
	.incbin "data/maps/CaveOfOrigin_1F/map.bin"

	.align 2
CaveOfOrigin_1F_MapAttributes::
	.4byte 0x17
	.4byte 0x17
	.4byte CaveOfOrigin_1F_MapBorder
	.4byte CaveOfOrigin_1F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Cave

CaveOfOrigin_B1F_MapBorder::
	.incbin "data/maps/CaveOfOrigin_B1F/border.bin"

CaveOfOrigin_B1F_MapBlockdata::
	.incbin "data/maps/CaveOfOrigin_B1F/map.bin"

	.align 2
CaveOfOrigin_B1F_MapAttributes::
	.4byte 0x17
	.4byte 0x17
	.4byte CaveOfOrigin_B1F_MapBorder
	.4byte CaveOfOrigin_B1F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Cave

CaveOfOrigin_B2F_MapBorder::
	.incbin "data/maps/CaveOfOrigin_B2F/border.bin"

CaveOfOrigin_B2F_MapBlockdata::
	.incbin "data/maps/CaveOfOrigin_B2F/map.bin"

	.align 2
CaveOfOrigin_B2F_MapAttributes::
	.4byte 0x15
	.4byte 0x15
	.4byte CaveOfOrigin_B2F_MapBorder
	.4byte CaveOfOrigin_B2F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Cave

CaveOfOrigin_B3F_MapBorder::
	.incbin "data/maps/CaveOfOrigin_B3F/border.bin"

CaveOfOrigin_B3F_MapBlockdata::
	.incbin "data/maps/CaveOfOrigin_B3F/map.bin"

	.align 2
CaveOfOrigin_B3F_MapAttributes::
	.4byte 0x13
	.4byte 0x15
	.4byte CaveOfOrigin_B3F_MapBorder
	.4byte CaveOfOrigin_B3F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Cave

CaveOfOrigin_B4F_MapBorder::
	.incbin "data/maps/CaveOfOrigin_B4F/border.bin"

CaveOfOrigin_B4F_MapBlockdata::
	.incbin "data/maps/CaveOfOrigin_B4F/map.bin"

	.align 2
CaveOfOrigin_B4F_MapAttributes::
	.4byte 0x13
	.4byte 0x13
	.4byte CaveOfOrigin_B4F_MapBorder
	.4byte CaveOfOrigin_B4F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Cave

VictoryRoad_1F_MapBorder::
	.incbin "data/maps/VictoryRoad_1F/border.bin"

VictoryRoad_1F_MapBlockdata::
	.incbin "data/maps/VictoryRoad_1F/map.bin"

	.align 2
VictoryRoad_1F_MapAttributes::
	.4byte 0x2e
	.4byte 0x2d
	.4byte VictoryRoad_1F_MapBorder
	.4byte VictoryRoad_1F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Cave

ShoalCave_LowTideEntranceRoom_MapBorder::
	.incbin "data/maps/ShoalCave_LowTideEntranceRoom/border.bin"

ShoalCave_LowTideEntranceRoom_MapBlockdata::
	.incbin "data/maps/ShoalCave_LowTideEntranceRoom/map.bin"

	.align 2
ShoalCave_LowTideEntranceRoom_MapAttributes::
	.4byte 0x23
	.4byte 0x23
	.4byte ShoalCave_LowTideEntranceRoom_MapBorder
	.4byte ShoalCave_LowTideEntranceRoom_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Cave

ShoalCave_LowTideInnerRoom_MapBorder::
	.incbin "data/maps/ShoalCave_LowTideInnerRoom/border.bin"

ShoalCave_LowTideInnerRoom_MapBlockdata::
	.incbin "data/maps/ShoalCave_LowTideInnerRoom/map.bin"

	.align 2
ShoalCave_LowTideInnerRoom_MapAttributes::
	.4byte 0x2e
	.4byte 0x26
	.4byte ShoalCave_LowTideInnerRoom_MapBorder
	.4byte ShoalCave_LowTideInnerRoom_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Cave

ShoalCave_LowTideStairsRoom_MapBorder::
	.incbin "data/maps/ShoalCave_LowTideStairsRoom/border.bin"

ShoalCave_LowTideStairsRoom_MapBlockdata::
	.incbin "data/maps/ShoalCave_LowTideStairsRoom/map.bin"

	.align 2
ShoalCave_LowTideStairsRoom_MapAttributes::
	.4byte 0x15
	.4byte 0xf
	.4byte ShoalCave_LowTideStairsRoom_MapBorder
	.4byte ShoalCave_LowTideStairsRoom_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Cave

ShoalCave_LowTideLowerRoom_MapBorder::
	.incbin "data/maps/ShoalCave_LowTideLowerRoom/border.bin"

ShoalCave_LowTideLowerRoom_MapBlockdata::
	.incbin "data/maps/ShoalCave_LowTideLowerRoom/map.bin"

	.align 2
ShoalCave_LowTideLowerRoom_MapAttributes::
	.4byte 0x1f
	.4byte 0xe
	.4byte ShoalCave_LowTideLowerRoom_MapBorder
	.4byte ShoalCave_LowTideLowerRoom_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Cave

ShoalCave_HighTideEntranceRoom_MapBorder::
	.incbin "data/maps/ShoalCave_HighTideEntranceRoom/border.bin"

ShoalCave_HighTideEntranceRoom_MapBlockdata::
	.incbin "data/maps/ShoalCave_HighTideEntranceRoom/map.bin"

	.align 2
ShoalCave_HighTideEntranceRoom_MapAttributes::
	.4byte 0x23
	.4byte 0x23
	.4byte ShoalCave_HighTideEntranceRoom_MapBorder
	.4byte ShoalCave_HighTideEntranceRoom_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Cave

ShoalCave_HighTideInnerRoom_MapBorder::
	.incbin "data/maps/ShoalCave_HighTideInnerRoom/border.bin"

ShoalCave_HighTideInnerRoom_MapBlockdata::
	.incbin "data/maps/ShoalCave_HighTideInnerRoom/map.bin"

	.align 2
ShoalCave_HighTideInnerRoom_MapAttributes::
	.4byte 0x2e
	.4byte 0x26
	.4byte ShoalCave_HighTideInnerRoom_MapBorder
	.4byte ShoalCave_HighTideInnerRoom_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Cave

UnknownMapBorder_082E55C8::
	.incbin "data/maps/UnknownMap_082E55C8/border.bin"

UnknownMapBlockdata_082E55C8::
	.incbin "data/maps/UnknownMap_082E55C8/map.bin"

	.align 2
UnknownMapAttributes_082E55C8::
	.4byte 0x1
	.4byte 0x1
	.4byte UnknownMapBorder_082E55C8
	.4byte UnknownMapBlockdata_082E55C8
	.4byte gTileset_General
	.4byte gTileset_Cave

UnknownMapBorder_082E55EC::
	.incbin "data/maps/UnknownMap_082E55EC/border.bin"

UnknownMapBlockdata_082E55EC::
	.incbin "data/maps/UnknownMap_082E55EC/map.bin"

	.align 2
UnknownMapAttributes_082E55EC::
	.4byte 0x1
	.4byte 0x1
	.4byte UnknownMapBorder_082E55EC
	.4byte UnknownMapBlockdata_082E55EC
	.4byte gTileset_General
	.4byte gTileset_Cave

UnknownMapBorder_082E5610::
	.incbin "data/maps/UnknownMap_082E5610/border.bin"

UnknownMapBlockdata_082E5610::
	.incbin "data/maps/UnknownMap_082E5610/map.bin"

	.align 2
UnknownMapAttributes_082E5610::
	.4byte 0x1
	.4byte 0x1
	.4byte UnknownMapBorder_082E5610
	.4byte UnknownMapBlockdata_082E5610
	.4byte gTileset_General
	.4byte gTileset_Cave

UnknownMapBorder_082E5634::
	.incbin "data/maps/UnknownMap_082E5634/border.bin"

UnknownMapBlockdata_082E5634::
	.incbin "data/maps/UnknownMap_082E5634/map.bin"

	.align 2
UnknownMapAttributes_082E5634::
	.4byte 0x1
	.4byte 0x1
	.4byte UnknownMapBorder_082E5634
	.4byte UnknownMapBlockdata_082E5634
	.4byte gTileset_General
	.4byte gTileset_Cave

UnknownMapBorder_082E5658::
	.incbin "data/maps/UnknownMap_082E5658/border.bin"

UnknownMapBlockdata_082E5658::
	.incbin "data/maps/UnknownMap_082E5658/map.bin"

	.align 2
UnknownMapAttributes_082E5658::
	.4byte 0x1
	.4byte 0x1
	.4byte UnknownMapBorder_082E5658
	.4byte UnknownMapBlockdata_082E5658
	.4byte gTileset_General
	.4byte gTileset_Cave

UnknownMapBorder_082E567C::
	.incbin "data/maps/UnknownMap_082E567C/border.bin"

UnknownMapBlockdata_082E567C::
	.incbin "data/maps/UnknownMap_082E567C/map.bin"

	.align 2
UnknownMapAttributes_082E567C::
	.4byte 0x1
	.4byte 0x1
	.4byte UnknownMapBorder_082E567C
	.4byte UnknownMapBlockdata_082E567C
	.4byte gTileset_General
	.4byte gTileset_Cave

UnknownMapBorder_082E56A0::
	.incbin "data/maps/UnknownMap_082E56A0/border.bin"

UnknownMapBlockdata_082E56A0::
	.incbin "data/maps/UnknownMap_082E56A0/map.bin"

	.align 2
UnknownMapAttributes_082E56A0::
	.4byte 0x1
	.4byte 0x1
	.4byte UnknownMapBorder_082E56A0
	.4byte UnknownMapBlockdata_082E56A0
	.4byte gTileset_General
	.4byte gTileset_Cave

UnknownMapBorder_082E56C4::
	.incbin "data/maps/UnknownMap_082E56C4/border.bin"

UnknownMapBlockdata_082E56C4::
	.incbin "data/maps/UnknownMap_082E56C4/map.bin"

	.align 2
UnknownMapAttributes_082E56C4::
	.4byte 0x1
	.4byte 0x1
	.4byte UnknownMapBorder_082E56C4
	.4byte UnknownMapBlockdata_082E56C4
	.4byte gTileset_General
	.4byte gTileset_Cave

UnknownMapBorder_082E56E8::
	.incbin "data/maps/UnknownMap_082E56E8/border.bin"

UnknownMapBlockdata_082E56E8::
	.incbin "data/maps/UnknownMap_082E56E8/map.bin"

	.align 2
UnknownMapAttributes_082E56E8::
	.4byte 0x1
	.4byte 0x1
	.4byte UnknownMapBorder_082E56E8
	.4byte UnknownMapBlockdata_082E56E8
	.4byte gTileset_General
	.4byte gTileset_Cave

UnknownMapBorder_082E570C::
	.incbin "data/maps/UnknownMap_082E570C/border.bin"

UnknownMapBlockdata_082E570C::
	.incbin "data/maps/UnknownMap_082E570C/map.bin"

	.align 2
UnknownMapAttributes_082E570C::
	.4byte 0x1
	.4byte 0x1
	.4byte UnknownMapBorder_082E570C
	.4byte UnknownMapBlockdata_082E570C
	.4byte gTileset_General
	.4byte gTileset_Cave

UnknownMapBorder_082E5730::
	.incbin "data/maps/UnknownMap_082E5730/border.bin"

UnknownMapBlockdata_082E5730::
	.incbin "data/maps/UnknownMap_082E5730/map.bin"

	.align 2
UnknownMapAttributes_082E5730::
	.4byte 0x1
	.4byte 0x1
	.4byte UnknownMapBorder_082E5730
	.4byte UnknownMapBlockdata_082E5730
	.4byte gTileset_General
	.4byte gTileset_Cave

UnknownMapBorder_082E5754::
	.incbin "data/maps/UnknownMap_082E5754/border.bin"

UnknownMapBlockdata_082E5754::
	.incbin "data/maps/UnknownMap_082E5754/map.bin"

	.align 2
UnknownMapAttributes_082E5754::
	.4byte 0x1
	.4byte 0x1
	.4byte UnknownMapBorder_082E5754
	.4byte UnknownMapBlockdata_082E5754
	.4byte gTileset_General
	.4byte gTileset_Cave

UnknownMapBorder_082E5778::
	.incbin "data/maps/UnknownMap_082E5778/border.bin"

UnknownMapBlockdata_082E5778::
	.incbin "data/maps/UnknownMap_082E5778/map.bin"

	.align 2
UnknownMapAttributes_082E5778::
	.4byte 0x1
	.4byte 0x1
	.4byte UnknownMapBorder_082E5778
	.4byte UnknownMapBlockdata_082E5778
	.4byte gTileset_General
	.4byte gTileset_Cave

UnknownMapBorder_082E579C::
	.incbin "data/maps/UnknownMap_082E579C/border.bin"

UnknownMapBlockdata_082E579C::
	.incbin "data/maps/UnknownMap_082E579C/map.bin"

	.align 2
UnknownMapAttributes_082E579C::
	.4byte 0x1
	.4byte 0x1
	.4byte UnknownMapBorder_082E579C
	.4byte UnknownMapBlockdata_082E579C
	.4byte gTileset_General
	.4byte gTileset_Cave

NewMauville_Entrance_MapBorder::
	.incbin "data/maps/NewMauville_Entrance/border.bin"

NewMauville_Entrance_MapBlockdata::
	.incbin "data/maps/NewMauville_Entrance/map.bin"

	.align 2
NewMauville_Entrance_MapAttributes::
	.4byte 0x9
	.4byte 0x9
	.4byte NewMauville_Entrance_MapBorder
	.4byte NewMauville_Entrance_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Facility

NewMauville_Inside_MapBorder::
	.incbin "data/maps/NewMauville_Inside/border.bin"

NewMauville_Inside_MapBlockdata::
	.incbin "data/maps/NewMauville_Inside/map.bin"

	.align 2
NewMauville_Inside_MapAttributes::
	.4byte 0x29
	.4byte 0x29
	.4byte NewMauville_Inside_MapBorder
	.4byte NewMauville_Inside_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_BikeShop

AbandonedShip_Deck_MapBorder::
	.incbin "data/maps/AbandonedShip_Deck/border.bin"

AbandonedShip_Deck_MapBlockdata::
	.incbin "data/maps/AbandonedShip_Deck/map.bin"

	.align 2
AbandonedShip_Deck_MapAttributes::
	.4byte 0x17
	.4byte 0x15
	.4byte AbandonedShip_Deck_MapBorder
	.4byte AbandonedShip_Deck_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Facility

AbandonedShip_Corridors_1F_MapBorder::
	.incbin "data/maps/AbandonedShip_Corridors_1F/border.bin"

AbandonedShip_Corridors_1F_MapBlockdata::
	.incbin "data/maps/AbandonedShip_Corridors_1F/map.bin"

	.align 2
AbandonedShip_Corridors_1F_MapAttributes::
	.4byte 0x12
	.4byte 0xc
	.4byte AbandonedShip_Corridors_1F_MapBorder
	.4byte AbandonedShip_Corridors_1F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Ship

AbandonedShip_Rooms_1F_MapBorder::
	.incbin "data/maps/AbandonedShip_Rooms_1F/border.bin"

AbandonedShip_Rooms_1F_MapBlockdata::
	.incbin "data/maps/AbandonedShip_Rooms_1F/map.bin"

	.align 2
AbandonedShip_Rooms_1F_MapAttributes::
	.4byte 0x12
	.4byte 0x11
	.4byte AbandonedShip_Rooms_1F_MapBorder
	.4byte AbandonedShip_Rooms_1F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Ship

AbandonedShip_Corridors_B1F_MapBorder::
	.incbin "data/maps/AbandonedShip_Corridors_B1F/border.bin"

AbandonedShip_Corridors_B1F_MapBlockdata::
	.incbin "data/maps/AbandonedShip_Corridors_B1F/map.bin"

	.align 2
AbandonedShip_Corridors_B1F_MapAttributes::
	.4byte 0xd
	.4byte 0xa
	.4byte AbandonedShip_Corridors_B1F_MapBorder
	.4byte AbandonedShip_Corridors_B1F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Ship

AbandonedShip_Rooms_B1F_MapBorder::
	.incbin "data/maps/AbandonedShip_Rooms_B1F/border.bin"

AbandonedShip_Rooms_B1F_MapBlockdata::
	.incbin "data/maps/AbandonedShip_Rooms_B1F/map.bin"

	.align 2
AbandonedShip_Rooms_B1F_MapAttributes::
	.4byte 0x1b
	.4byte 0x8
	.4byte AbandonedShip_Rooms_B1F_MapBorder
	.4byte AbandonedShip_Rooms_B1F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Ship

AbandonedShip_Rooms2_B1F_MapBorder::
	.incbin "data/maps/AbandonedShip_Rooms2_B1F/border.bin"

AbandonedShip_Rooms2_B1F_MapBlockdata::
	.incbin "data/maps/AbandonedShip_Rooms2_B1F/map.bin"

	.align 2
AbandonedShip_Rooms2_B1F_MapAttributes::
	.4byte 0x12
	.4byte 0x8
	.4byte AbandonedShip_Rooms2_B1F_MapBorder
	.4byte AbandonedShip_Rooms2_B1F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Ship

AbandonedShip_Underwater1_MapBorder::
	.incbin "data/maps/AbandonedShip_Underwater1/border.bin"

AbandonedShip_Underwater1_MapBlockdata::
	.incbin "data/maps/AbandonedShip_Underwater1/map.bin"

	.align 2
AbandonedShip_Underwater1_MapAttributes::
	.4byte 0x8
	.4byte 0x8
	.4byte AbandonedShip_Underwater1_MapBorder
	.4byte AbandonedShip_Underwater1_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Ship

AbandonedShip_Room_B1F_MapBorder::
	.incbin "data/maps/AbandonedShip_Room_B1F/border.bin"

AbandonedShip_Room_B1F_MapBlockdata::
	.incbin "data/maps/AbandonedShip_Room_B1F/map.bin"

	.align 2
AbandonedShip_Room_B1F_MapAttributes::
	.4byte 0x9
	.4byte 0x8
	.4byte AbandonedShip_Room_B1F_MapBorder
	.4byte AbandonedShip_Room_B1F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Ship

AbandonedShip_Rooms2_1F_MapBorder::
	.incbin "data/maps/AbandonedShip_Rooms2_1F/border.bin"

AbandonedShip_Rooms2_1F_MapBlockdata::
	.incbin "data/maps/AbandonedShip_Rooms2_1F/map.bin"

	.align 2
AbandonedShip_Rooms2_1F_MapAttributes::
	.4byte 0x9
	.4byte 0x11
	.4byte AbandonedShip_Rooms2_1F_MapBorder
	.4byte AbandonedShip_Rooms2_1F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Ship

AbandonedShip_CaptainsOffice_MapBorder::
	.incbin "data/maps/AbandonedShip_CaptainsOffice/border.bin"

AbandonedShip_CaptainsOffice_MapBlockdata::
	.incbin "data/maps/AbandonedShip_CaptainsOffice/map.bin"

	.align 2
AbandonedShip_CaptainsOffice_MapAttributes::
	.4byte 0x9
	.4byte 0x7
	.4byte AbandonedShip_CaptainsOffice_MapBorder
	.4byte AbandonedShip_CaptainsOffice_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Facility

AbandonedShip_Underwater2_MapBorder::
	.incbin "data/maps/AbandonedShip_Underwater2/border.bin"

AbandonedShip_Underwater2_MapBlockdata::
	.incbin "data/maps/AbandonedShip_Underwater2/map.bin"

	.align 2
AbandonedShip_Underwater2_MapAttributes::
	.4byte 0x15
	.4byte 0x7
	.4byte AbandonedShip_Underwater2_MapBorder
	.4byte AbandonedShip_Underwater2_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Ship

SecretBase_RedCave1_MapBorder::
	.incbin "data/maps/SecretBase_RedCave1/border.bin"

SecretBase_RedCave1_MapBlockdata::
	.incbin "data/maps/SecretBase_RedCave1/map.bin"

	.align 2
SecretBase_RedCave1_MapAttributes::
	.4byte 0xb
	.4byte 0x9
	.4byte SecretBase_RedCave1_MapBorder
	.4byte SecretBase_RedCave1_MapBlockdata
	.4byte gTileset_SecretBase
	.4byte gTileset_SecretBaseRedCave

SecretBase_BrownCave1_MapBorder::
	.incbin "data/maps/SecretBase_BrownCave1/border.bin"

SecretBase_BrownCave1_MapBlockdata::
	.incbin "data/maps/SecretBase_BrownCave1/map.bin"

	.align 2
SecretBase_BrownCave1_MapAttributes::
	.4byte 0xb
	.4byte 0x9
	.4byte SecretBase_BrownCave1_MapBorder
	.4byte SecretBase_BrownCave1_MapBlockdata
	.4byte gTileset_SecretBase
	.4byte gTileset_SecretBaseBrownCave

SecretBase_BlueCave1_MapBorder::
	.incbin "data/maps/SecretBase_BlueCave1/border.bin"

SecretBase_BlueCave1_MapBlockdata::
	.incbin "data/maps/SecretBase_BlueCave1/map.bin"

	.align 2
SecretBase_BlueCave1_MapAttributes::
	.4byte 0xb
	.4byte 0x9
	.4byte SecretBase_BlueCave1_MapBorder
	.4byte SecretBase_BlueCave1_MapBlockdata
	.4byte gTileset_SecretBase
	.4byte gTileset_SecretBaseBlueCave

SecretBase_YellowCave1_MapBorder::
	.incbin "data/maps/SecretBase_YellowCave1/border.bin"

SecretBase_YellowCave1_MapBlockdata::
	.incbin "data/maps/SecretBase_YellowCave1/map.bin"

	.align 2
SecretBase_YellowCave1_MapAttributes::
	.4byte 0xb
	.4byte 0x9
	.4byte SecretBase_YellowCave1_MapBorder
	.4byte SecretBase_YellowCave1_MapBlockdata
	.4byte gTileset_SecretBase
	.4byte gTileset_SecretBaseYellowCave

SecretBase_Tree1_MapBorder::
	.incbin "data/maps/SecretBase_Tree1/border.bin"

SecretBase_Tree1_MapBlockdata::
	.incbin "data/maps/SecretBase_Tree1/map.bin"

	.align 2
SecretBase_Tree1_MapAttributes::
	.4byte 0xb
	.4byte 0x9
	.4byte SecretBase_Tree1_MapBorder
	.4byte SecretBase_Tree1_MapBlockdata
	.4byte gTileset_SecretBase
	.4byte gTileset_SecretBaseTree

SecretBase_Shrub1_MapBorder::
	.incbin "data/maps/SecretBase_Shrub1/border.bin"

SecretBase_Shrub1_MapBlockdata::
	.incbin "data/maps/SecretBase_Shrub1/map.bin"

	.align 2
SecretBase_Shrub1_MapAttributes::
	.4byte 0xb
	.4byte 0x9
	.4byte SecretBase_Shrub1_MapBorder
	.4byte SecretBase_Shrub1_MapBlockdata
	.4byte gTileset_SecretBase
	.4byte gTileset_SecretBaseShrub

SecretBase_RedCave2_MapBorder::
	.incbin "data/maps/SecretBase_RedCave2/border.bin"

SecretBase_RedCave2_MapBlockdata::
	.incbin "data/maps/SecretBase_RedCave2/map.bin"

	.align 2
SecretBase_RedCave2_MapAttributes::
	.4byte 0x7
	.4byte 0x10
	.4byte SecretBase_RedCave2_MapBorder
	.4byte SecretBase_RedCave2_MapBlockdata
	.4byte gTileset_SecretBase
	.4byte gTileset_SecretBaseRedCave

SecretBase_BrownCave2_MapBorder::
	.incbin "data/maps/SecretBase_BrownCave2/border.bin"

SecretBase_BrownCave2_MapBlockdata::
	.incbin "data/maps/SecretBase_BrownCave2/map.bin"

	.align 2
SecretBase_BrownCave2_MapAttributes::
	.4byte 0xe
	.4byte 0x9
	.4byte SecretBase_BrownCave2_MapBorder
	.4byte SecretBase_BrownCave2_MapBlockdata
	.4byte gTileset_SecretBase
	.4byte gTileset_SecretBaseBrownCave

SecretBase_BlueCave2_MapBorder::
	.incbin "data/maps/SecretBase_BlueCave2/border.bin"

SecretBase_BlueCave2_MapBlockdata::
	.incbin "data/maps/SecretBase_BlueCave2/map.bin"

	.align 2
SecretBase_BlueCave2_MapAttributes::
	.4byte 0xf
	.4byte 0x7
	.4byte SecretBase_BlueCave2_MapBorder
	.4byte SecretBase_BlueCave2_MapBlockdata
	.4byte gTileset_SecretBase
	.4byte gTileset_SecretBaseBlueCave

SecretBase_YellowCave2_MapBorder::
	.incbin "data/maps/SecretBase_YellowCave2/border.bin"

SecretBase_YellowCave2_MapBlockdata::
	.incbin "data/maps/SecretBase_YellowCave2/map.bin"

	.align 2
SecretBase_YellowCave2_MapAttributes::
	.4byte 0xe
	.4byte 0x9
	.4byte SecretBase_YellowCave2_MapBorder
	.4byte SecretBase_YellowCave2_MapBlockdata
	.4byte gTileset_SecretBase
	.4byte gTileset_SecretBaseYellowCave

SecretBase_Tree2_MapBorder::
	.incbin "data/maps/SecretBase_Tree2/border.bin"

SecretBase_Tree2_MapBlockdata::
	.incbin "data/maps/SecretBase_Tree2/map.bin"

	.align 2
SecretBase_Tree2_MapAttributes::
	.4byte 0x7
	.4byte 0x10
	.4byte SecretBase_Tree2_MapBorder
	.4byte SecretBase_Tree2_MapBlockdata
	.4byte gTileset_SecretBase
	.4byte gTileset_SecretBaseTree

SecretBase_Shrub2_MapBorder::
	.incbin "data/maps/SecretBase_Shrub2/border.bin"

SecretBase_Shrub2_MapBlockdata::
	.incbin "data/maps/SecretBase_Shrub2/map.bin"

	.align 2
SecretBase_Shrub2_MapAttributes::
	.4byte 0xf
	.4byte 0x7
	.4byte SecretBase_Shrub2_MapBorder
	.4byte SecretBase_Shrub2_MapBlockdata
	.4byte gTileset_SecretBase
	.4byte gTileset_SecretBaseShrub

SecretBase_RedCave3_MapBorder::
	.incbin "data/maps/SecretBase_RedCave3/border.bin"

SecretBase_RedCave3_MapBlockdata::
	.incbin "data/maps/SecretBase_RedCave3/map.bin"

	.align 2
SecretBase_RedCave3_MapAttributes::
	.4byte 0xf
	.4byte 0x8
	.4byte SecretBase_RedCave3_MapBorder
	.4byte SecretBase_RedCave3_MapBlockdata
	.4byte gTileset_SecretBase
	.4byte gTileset_SecretBaseRedCave

SecretBase_BrownCave3_MapBorder::
	.incbin "data/maps/SecretBase_BrownCave3/border.bin"

SecretBase_BrownCave3_MapBlockdata::
	.incbin "data/maps/SecretBase_BrownCave3/map.bin"

	.align 2
SecretBase_BrownCave3_MapAttributes::
	.4byte 0xf
	.4byte 0xb
	.4byte SecretBase_BrownCave3_MapBorder
	.4byte SecretBase_BrownCave3_MapBlockdata
	.4byte gTileset_SecretBase
	.4byte gTileset_SecretBaseBrownCave

SecretBase_BlueCave3_MapBorder::
	.incbin "data/maps/SecretBase_BlueCave3/border.bin"

SecretBase_BlueCave3_MapBlockdata::
	.incbin "data/maps/SecretBase_BlueCave3/map.bin"

	.align 2
SecretBase_BlueCave3_MapAttributes::
	.4byte 0xa
	.4byte 0x11
	.4byte SecretBase_BlueCave3_MapBorder
	.4byte SecretBase_BlueCave3_MapBlockdata
	.4byte gTileset_SecretBase
	.4byte gTileset_SecretBaseBlueCave

SecretBase_YellowCave3_MapBorder::
	.incbin "data/maps/SecretBase_YellowCave3/border.bin"

SecretBase_YellowCave3_MapBlockdata::
	.incbin "data/maps/SecretBase_YellowCave3/map.bin"

	.align 2
SecretBase_YellowCave3_MapAttributes::
	.4byte 0xc
	.4byte 0xb
	.4byte SecretBase_YellowCave3_MapBorder
	.4byte SecretBase_YellowCave3_MapBlockdata
	.4byte gTileset_SecretBase
	.4byte gTileset_SecretBaseYellowCave

SecretBase_Tree3_MapBorder::
	.incbin "data/maps/SecretBase_Tree3/border.bin"

SecretBase_Tree3_MapBlockdata::
	.incbin "data/maps/SecretBase_Tree3/map.bin"

	.align 2
SecretBase_Tree3_MapAttributes::
	.4byte 0x11
	.4byte 0x8
	.4byte SecretBase_Tree3_MapBorder
	.4byte SecretBase_Tree3_MapBlockdata
	.4byte gTileset_SecretBase
	.4byte gTileset_SecretBaseTree

SecretBase_Shrub3_MapBorder::
	.incbin "data/maps/SecretBase_Shrub3/border.bin"

SecretBase_Shrub3_MapBlockdata::
	.incbin "data/maps/SecretBase_Shrub3/map.bin"

	.align 2
SecretBase_Shrub3_MapAttributes::
	.4byte 0xd
	.4byte 0xb
	.4byte SecretBase_Shrub3_MapBorder
	.4byte SecretBase_Shrub3_MapBlockdata
	.4byte gTileset_SecretBase
	.4byte gTileset_SecretBaseShrub

SecretBase_RedCave4_MapBorder::
	.incbin "data/maps/SecretBase_RedCave4/border.bin"

SecretBase_RedCave4_MapBlockdata::
	.incbin "data/maps/SecretBase_RedCave4/map.bin"

	.align 2
SecretBase_RedCave4_MapAttributes::
	.4byte 0x9
	.4byte 0xf
	.4byte SecretBase_RedCave4_MapBorder
	.4byte SecretBase_RedCave4_MapBlockdata
	.4byte gTileset_SecretBase
	.4byte gTileset_SecretBaseRedCave

SecretBase_BrownCave4_MapBorder::
	.incbin "data/maps/SecretBase_BrownCave4/border.bin"

SecretBase_BrownCave4_MapBlockdata::
	.incbin "data/maps/SecretBase_BrownCave4/map.bin"

	.align 2
SecretBase_BrownCave4_MapAttributes::
	.4byte 0xe
	.4byte 0xc
	.4byte SecretBase_BrownCave4_MapBorder
	.4byte SecretBase_BrownCave4_MapBlockdata
	.4byte gTileset_SecretBase
	.4byte gTileset_SecretBaseBrownCave

SecretBase_BlueCave4_MapBorder::
	.incbin "data/maps/SecretBase_BlueCave4/border.bin"

SecretBase_BlueCave4_MapBlockdata::
	.incbin "data/maps/SecretBase_BlueCave4/map.bin"

	.align 2
SecretBase_BlueCave4_MapAttributes::
	.4byte 0x9
	.4byte 0x11
	.4byte SecretBase_BlueCave4_MapBorder
	.4byte SecretBase_BlueCave4_MapBlockdata
	.4byte gTileset_SecretBase
	.4byte gTileset_SecretBaseBlueCave

SecretBase_YellowCave4_MapBorder::
	.incbin "data/maps/SecretBase_YellowCave4/border.bin"

SecretBase_YellowCave4_MapBlockdata::
	.incbin "data/maps/SecretBase_YellowCave4/map.bin"

	.align 2
SecretBase_YellowCave4_MapAttributes::
	.4byte 0xd
	.4byte 0xe
	.4byte SecretBase_YellowCave4_MapBorder
	.4byte SecretBase_YellowCave4_MapBlockdata
	.4byte gTileset_SecretBase
	.4byte gTileset_SecretBaseYellowCave

SecretBase_Tree4_MapBorder::
	.incbin "data/maps/SecretBase_Tree4/border.bin"

SecretBase_Tree4_MapBlockdata::
	.incbin "data/maps/SecretBase_Tree4/map.bin"

	.align 2
SecretBase_Tree4_MapAttributes::
	.4byte 0xe
	.4byte 0xe
	.4byte SecretBase_Tree4_MapBorder
	.4byte SecretBase_Tree4_MapBlockdata
	.4byte gTileset_SecretBase
	.4byte gTileset_SecretBaseTree

SecretBase_Shrub4_MapBorder::
	.incbin "data/maps/SecretBase_Shrub4/border.bin"

SecretBase_Shrub4_MapBlockdata::
	.incbin "data/maps/SecretBase_Shrub4/map.bin"

	.align 2
SecretBase_Shrub4_MapAttributes::
	.4byte 0xe
	.4byte 0xb
	.4byte SecretBase_Shrub4_MapBorder
	.4byte SecretBase_Shrub4_MapBlockdata
	.4byte gTileset_SecretBase
	.4byte gTileset_SecretBaseShrub

SingleBattleColosseum_MapBorder::
	.incbin "data/maps/SingleBattleColosseum/border.bin"

SingleBattleColosseum_MapBlockdata::
	.incbin "data/maps/SingleBattleColosseum/map.bin"

	.align 2
SingleBattleColosseum_MapAttributes::
	.4byte 0xe
	.4byte 0x9
	.4byte SingleBattleColosseum_MapBorder
	.4byte SingleBattleColosseum_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_CableClub

TradeCenter_MapBorder::
	.incbin "data/maps/TradeCenter/border.bin"

TradeCenter_MapBlockdata::
	.incbin "data/maps/TradeCenter/map.bin"

	.align 2
TradeCenter_MapAttributes::
	.4byte 0xc
	.4byte 0x9
	.4byte TradeCenter_MapBorder
	.4byte TradeCenter_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_CableClub

RecordCorner_MapBorder::
	.incbin "data/maps/RecordCorner/border.bin"

RecordCorner_MapBlockdata::
	.incbin "data/maps/RecordCorner/map.bin"

	.align 2
RecordCorner_MapAttributes::
	.4byte 0x14
	.4byte 0xa
	.4byte RecordCorner_MapBorder
	.4byte RecordCorner_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_CableClub

DoubleBattleColosseum_MapBorder::
	.incbin "data/maps/DoubleBattleColosseum/border.bin"

DoubleBattleColosseum_MapBlockdata::
	.incbin "data/maps/DoubleBattleColosseum/map.bin"

	.align 2
DoubleBattleColosseum_MapAttributes::
	.4byte 0xe
	.4byte 0x9
	.4byte DoubleBattleColosseum_MapBorder
	.4byte DoubleBattleColosseum_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_CableClub

LinkContestRoom1_MapBorder::
	.incbin "data/maps/LinkContestRoom1/border.bin"

LinkContestRoom1_MapBlockdata::
	.incbin "data/maps/LinkContestRoom1/map.bin"

	.align 2
LinkContestRoom1_MapAttributes::
	.4byte 0xf
	.4byte 0xb
	.4byte LinkContestRoom1_MapBorder
	.4byte LinkContestRoom1_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Contest

UnknownMap_25_29_MapBorder::
	.incbin "data/maps/UnknownMap_25_29/border.bin"

UnknownMap_25_29_MapBlockdata::
	.incbin "data/maps/UnknownMap_25_29/map.bin"

	.align 2
UnknownMap_25_29_MapAttributes::
	.4byte 0x1
	.4byte 0x1
	.4byte UnknownMap_25_29_MapBorder
	.4byte UnknownMap_25_29_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_Contest

UnknownMap_25_30_MapBorder::
	.incbin "data/maps/UnknownMap_25_30/border.bin"

UnknownMap_25_30_MapBlockdata::
	.incbin "data/maps/UnknownMap_25_30/map.bin"

	.align 2
UnknownMap_25_30_MapAttributes::
	.4byte 0x1
	.4byte 0x1
	.4byte UnknownMap_25_30_MapBorder
	.4byte UnknownMap_25_30_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_Contest

UnknownMap_25_31_MapBorder::
	.incbin "data/maps/UnknownMap_25_31/border.bin"

UnknownMap_25_31_MapBlockdata::
	.incbin "data/maps/UnknownMap_25_31/map.bin"

	.align 2
UnknownMap_25_31_MapAttributes::
	.4byte 0x1
	.4byte 0x1
	.4byte UnknownMap_25_31_MapBorder
	.4byte UnknownMap_25_31_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_Contest

UnknownMap_25_32_MapBorder::
	.incbin "data/maps/UnknownMap_25_32/border.bin"

UnknownMap_25_32_MapBlockdata::
	.incbin "data/maps/UnknownMap_25_32/map.bin"

	.align 2
UnknownMap_25_32_MapAttributes::
	.4byte 0x1
	.4byte 0x1
	.4byte UnknownMap_25_32_MapBorder
	.4byte UnknownMap_25_32_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_Contest

UnknownMap_25_33_MapBorder::
	.incbin "data/maps/UnknownMap_25_33/border.bin"

UnknownMap_25_33_MapBlockdata::
	.incbin "data/maps/UnknownMap_25_33/map.bin"

	.align 2
UnknownMap_25_33_MapAttributes::
	.4byte 0x1
	.4byte 0x1
	.4byte UnknownMap_25_33_MapBorder
	.4byte UnknownMap_25_33_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_Contest

UnknownMap_25_34_MapBorder::
	.incbin "data/maps/UnknownMap_25_34/border.bin"

UnknownMap_25_34_MapBlockdata::
	.incbin "data/maps/UnknownMap_25_34/map.bin"

	.align 2
UnknownMap_25_34_MapAttributes::
	.4byte 0x1
	.4byte 0x1
	.4byte UnknownMap_25_34_MapBorder
	.4byte UnknownMap_25_34_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_Contest

LinkContestRoom2_MapBorder::
	.incbin "data/maps/LinkContestRoom2/border.bin"

LinkContestRoom2_MapBlockdata::
	.incbin "data/maps/LinkContestRoom2/map.bin"

	.align 2
LinkContestRoom2_MapAttributes::
	.4byte 0xf
	.4byte 0xb
	.4byte LinkContestRoom2_MapBorder
	.4byte LinkContestRoom2_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Contest

LinkContestRoom3_MapBorder::
	.incbin "data/maps/LinkContestRoom3/border.bin"

LinkContestRoom3_MapBlockdata::
	.incbin "data/maps/LinkContestRoom3/map.bin"

	.align 2
LinkContestRoom3_MapAttributes::
	.4byte 0xf
	.4byte 0xb
	.4byte LinkContestRoom3_MapBorder
	.4byte LinkContestRoom3_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Contest

LinkContestRoom4_MapBorder::
	.incbin "data/maps/LinkContestRoom4/border.bin"

LinkContestRoom4_MapBlockdata::
	.incbin "data/maps/LinkContestRoom4/map.bin"

	.align 2
LinkContestRoom4_MapAttributes::
	.4byte 0xf
	.4byte 0xb
	.4byte LinkContestRoom4_MapBorder
	.4byte LinkContestRoom4_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Contest

LinkContestRoom5_MapBorder::
	.incbin "data/maps/LinkContestRoom5/border.bin"

LinkContestRoom5_MapBlockdata::
	.incbin "data/maps/LinkContestRoom5/map.bin"

	.align 2
LinkContestRoom5_MapAttributes::
	.4byte 0xf
	.4byte 0xb
	.4byte LinkContestRoom5_MapBorder
	.4byte LinkContestRoom5_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Contest

LinkContestRoom6_MapBorder::
	.incbin "data/maps/LinkContestRoom6/border.bin"

LinkContestRoom6_MapBlockdata::
	.incbin "data/maps/LinkContestRoom6/map.bin"

	.align 2
LinkContestRoom6_MapAttributes::
	.4byte 0xf
	.4byte 0xb
	.4byte LinkContestRoom6_MapBorder
	.4byte LinkContestRoom6_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Contest

InsideOfTruck_MapBorder::
	.incbin "data/maps/InsideOfTruck/border.bin"

InsideOfTruck_MapBlockdata::
	.incbin "data/maps/InsideOfTruck/map.bin"

	.align 2
InsideOfTruck_MapAttributes::
	.4byte 0x5
	.4byte 0x5
	.4byte InsideOfTruck_MapBorder
	.4byte InsideOfTruck_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_InsideOfTruck

SafariZone_Northwest_MapBorder::
	.incbin "data/maps/SafariZone_Northwest/border.bin"

SafariZone_Northwest_MapBlockdata::
	.incbin "data/maps/SafariZone_Northwest/map.bin"

	.align 2
SafariZone_Northwest_MapAttributes::
	.4byte 0x28
	.4byte 0x28
	.4byte SafariZone_Northwest_MapBorder
	.4byte SafariZone_Northwest_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Lilycove

SafariZone_Northeast_MapBorder::
	.incbin "data/maps/SafariZone_Northeast/border.bin"

SafariZone_Northeast_MapBlockdata::
	.incbin "data/maps/SafariZone_Northeast/map.bin"

	.align 2
SafariZone_Northeast_MapAttributes::
	.4byte 0x28
	.4byte 0x28
	.4byte SafariZone_Northeast_MapBorder
	.4byte SafariZone_Northeast_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Lilycove

SafariZone_Southwest_MapBorder::
	.incbin "data/maps/SafariZone_Southwest/border.bin"

SafariZone_Southwest_MapBlockdata::
	.incbin "data/maps/SafariZone_Southwest/map.bin"

	.align 2
SafariZone_Southwest_MapAttributes::
	.4byte 0x28
	.4byte 0x28
	.4byte SafariZone_Southwest_MapBorder
	.4byte SafariZone_Southwest_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Lilycove

SafariZone_Southeast_MapBorder::
	.incbin "data/maps/SafariZone_Southeast/border.bin"

SafariZone_Southeast_MapBlockdata::
	.incbin "data/maps/SafariZone_Southeast/map.bin"

	.align 2
SafariZone_Southeast_MapAttributes::
	.4byte 0x28
	.4byte 0x28
	.4byte SafariZone_Southeast_MapBorder
	.4byte SafariZone_Southeast_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Lilycove

UnknownMapBorder_082EDF30::
	.incbin "data/maps/UnknownMap_082EDF30/border.bin"

UnknownMapBlockdata_082EDF30::
	.incbin "data/maps/UnknownMap_082EDF30/map.bin"

	.align 2
UnknownMapAttributes_082EDF30::
	.4byte 0x3A
	.4byte 0x1A
	.4byte UnknownMapBorder_082EDF30
	.4byte UnknownMapBlockdata_082EDF30
	.4byte gTileset_General
	.4byte 0

Route109_SeashoreHouse_MapBorder::
	.incbin "data/maps/Route109_SeashoreHouse/border.bin"

Route109_SeashoreHouse_MapBlockdata::
	.incbin "data/maps/Route109_SeashoreHouse/map.bin"

	.align 2
Route109_SeashoreHouse_MapAttributes::
	.4byte 0xf
	.4byte 0xa
	.4byte Route109_SeashoreHouse_MapBorder
	.4byte Route109_SeashoreHouse_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_SeashoreHouse

Route110_TrickHouseEntrance_MapBorder::
	.incbin "data/maps/Route110_TrickHouseEntrance/border.bin"

Route110_TrickHouseEntrance_MapBlockdata::
	.incbin "data/maps/Route110_TrickHouseEntrance/map.bin"

	.align 2
Route110_TrickHouseEntrance_MapAttributes::
	.4byte 0xc
	.4byte 0x8
	.4byte Route110_TrickHouseEntrance_MapBorder
	.4byte Route110_TrickHouseEntrance_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_GenericBuilding

Route110_TrickHouseEnd_MapBorder::
	.incbin "data/maps/Route110_TrickHouseEnd/border.bin"

Route110_TrickHouseEnd_MapBlockdata::
	.incbin "data/maps/Route110_TrickHouseEnd/map.bin"

	.align 2
Route110_TrickHouseEnd_MapAttributes::
	.4byte 0xc
	.4byte 0x8
	.4byte Route110_TrickHouseEnd_MapBorder
	.4byte Route110_TrickHouseEnd_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_GenericBuilding

Route110_TrickHouseCorridor_MapBorder::
	.incbin "data/maps/Route110_TrickHouseCorridor/border.bin"

Route110_TrickHouseCorridor_MapBlockdata::
	.incbin "data/maps/Route110_TrickHouseCorridor/map.bin"

	.align 2
Route110_TrickHouseCorridor_MapAttributes::
	.4byte 0xf
	.4byte 0x18
	.4byte Route110_TrickHouseCorridor_MapBorder
	.4byte Route110_TrickHouseCorridor_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_GenericBuilding

Route110_TrickHousePuzzle1_MapBorder::
	.incbin "data/maps/Route110_TrickHousePuzzle1/border.bin"

Route110_TrickHousePuzzle1_MapBlockdata::
	.incbin "data/maps/Route110_TrickHousePuzzle1/map.bin"

	.align 2
Route110_TrickHousePuzzle1_MapAttributes::
	.4byte 0xf
	.4byte 0x16
	.4byte Route110_TrickHousePuzzle1_MapBorder
	.4byte Route110_TrickHousePuzzle1_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_TrickHousePuzzle

Route110_TrickHousePuzzle2_MapBorder::
	.incbin "data/maps/Route110_TrickHousePuzzle2/border.bin"

Route110_TrickHousePuzzle2_MapBlockdata::
	.incbin "data/maps/Route110_TrickHousePuzzle2/map.bin"

	.align 2
Route110_TrickHousePuzzle2_MapAttributes::
	.4byte 0xf
	.4byte 0x16
	.4byte Route110_TrickHousePuzzle2_MapBorder
	.4byte Route110_TrickHousePuzzle2_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_TrickHousePuzzle

Route110_TrickHousePuzzle3_MapBorder::
	.incbin "data/maps/Route110_TrickHousePuzzle3/border.bin"

Route110_TrickHousePuzzle3_MapBlockdata::
	.incbin "data/maps/Route110_TrickHousePuzzle3/map.bin"

	.align 2
Route110_TrickHousePuzzle3_MapAttributes::
	.4byte 0xf
	.4byte 0x16
	.4byte Route110_TrickHousePuzzle3_MapBorder
	.4byte Route110_TrickHousePuzzle3_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_TrickHousePuzzle

Route110_TrickHousePuzzle4_MapBorder::
	.incbin "data/maps/Route110_TrickHousePuzzle4/border.bin"

Route110_TrickHousePuzzle4_MapBlockdata::
	.incbin "data/maps/Route110_TrickHousePuzzle4/map.bin"

	.align 2
Route110_TrickHousePuzzle4_MapAttributes::
	.4byte 0xf
	.4byte 0x16
	.4byte Route110_TrickHousePuzzle4_MapBorder
	.4byte Route110_TrickHousePuzzle4_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_TrickHousePuzzle

Route110_TrickHousePuzzle5_MapBorder::
	.incbin "data/maps/Route110_TrickHousePuzzle5/border.bin"

Route110_TrickHousePuzzle5_MapBlockdata::
	.incbin "data/maps/Route110_TrickHousePuzzle5/map.bin"

	.align 2
Route110_TrickHousePuzzle5_MapAttributes::
	.4byte 0xf
	.4byte 0x16
	.4byte Route110_TrickHousePuzzle5_MapBorder
	.4byte Route110_TrickHousePuzzle5_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_TrickHousePuzzle

Route110_TrickHousePuzzle6_MapBorder::
	.incbin "data/maps/Route110_TrickHousePuzzle6/border.bin"

Route110_TrickHousePuzzle6_MapBlockdata::
	.incbin "data/maps/Route110_TrickHousePuzzle6/map.bin"

	.align 2
Route110_TrickHousePuzzle6_MapAttributes::
	.4byte 0xf
	.4byte 0x16
	.4byte Route110_TrickHousePuzzle6_MapBorder
	.4byte Route110_TrickHousePuzzle6_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_TrickHousePuzzle

Route110_TrickHousePuzzle7_MapBorder::
	.incbin "data/maps/Route110_TrickHousePuzzle7/border.bin"

Route110_TrickHousePuzzle7_MapBlockdata::
	.incbin "data/maps/Route110_TrickHousePuzzle7/map.bin"

	.align 2
Route110_TrickHousePuzzle7_MapAttributes::
	.4byte 0xf
	.4byte 0x16
	.4byte Route110_TrickHousePuzzle7_MapBorder
	.4byte Route110_TrickHousePuzzle7_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_TrickHousePuzzle

Route110_TrickHousePuzzle8_MapBorder::
	.incbin "data/maps/Route110_TrickHousePuzzle8/border.bin"

Route110_TrickHousePuzzle8_MapBlockdata::
	.incbin "data/maps/Route110_TrickHousePuzzle8/map.bin"

	.align 2
Route110_TrickHousePuzzle8_MapAttributes::
	.4byte 0xf
	.4byte 0x16
	.4byte Route110_TrickHousePuzzle8_MapBorder
	.4byte Route110_TrickHousePuzzle8_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_TrickHousePuzzle

FortreeCity_DecorationShop_MapBorder::
	.incbin "data/maps/FortreeCity_DecorationShop/border.bin"

FortreeCity_DecorationShop_MapBlockdata::
	.incbin "data/maps/FortreeCity_DecorationShop/map.bin"

	.align 2
FortreeCity_DecorationShop_MapAttributes::
	.4byte 0x8
	.4byte 0x6
	.4byte FortreeCity_DecorationShop_MapBorder
	.4byte FortreeCity_DecorationShop_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_GenericBuilding

Route110_SeasideCyclingRoadSouthEntrance_MapBorder::
	.incbin "data/maps/Route110_SeasideCyclingRoadSouthEntrance/border.bin"

Route110_SeasideCyclingRoadSouthEntrance_MapBlockdata::
	.incbin "data/maps/Route110_SeasideCyclingRoadSouthEntrance/map.bin"

	.align 2
Route110_SeasideCyclingRoadNorthEntrance_MapAttributes::
Route110_SeasideCyclingRoadSouthEntrance_MapAttributes::
	.4byte 0xf
	.4byte 0x6
	.4byte Route110_SeasideCyclingRoadSouthEntrance_MapBorder
	.4byte Route110_SeasideCyclingRoadSouthEntrance_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_Shop

LilycoveCity_DepartmentStore_1F_MapBorder::
	.incbin "data/maps/LilycoveCity_DepartmentStore_1F/border.bin"

LilycoveCity_DepartmentStore_1F_MapBlockdata::
	.incbin "data/maps/LilycoveCity_DepartmentStore_1F/map.bin"

	.align 2
LilycoveCity_DepartmentStore_1F_MapAttributes::
	.4byte 0x12
	.4byte 0x8
	.4byte LilycoveCity_DepartmentStore_1F_MapBorder
	.4byte LilycoveCity_DepartmentStore_1F_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_Shop

LilycoveCity_DepartmentStore_2F_MapBorder::
	.incbin "data/maps/LilycoveCity_DepartmentStore_2F/border.bin"

LilycoveCity_DepartmentStore_2F_MapBlockdata::
	.incbin "data/maps/LilycoveCity_DepartmentStore_2F/map.bin"

	.align 2
LilycoveCity_DepartmentStore_2F_MapAttributes::
	.4byte 0x12
	.4byte 0x8
	.4byte LilycoveCity_DepartmentStore_2F_MapBorder
	.4byte LilycoveCity_DepartmentStore_2F_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_Shop

LilycoveCity_DepartmentStore_3F_MapBorder::
	.incbin "data/maps/LilycoveCity_DepartmentStore_3F/border.bin"

LilycoveCity_DepartmentStore_3F_MapBlockdata::
	.incbin "data/maps/LilycoveCity_DepartmentStore_3F/map.bin"

	.align 2
LilycoveCity_DepartmentStore_3F_MapAttributes::
	.4byte 0x12
	.4byte 0x8
	.4byte LilycoveCity_DepartmentStore_3F_MapBorder
	.4byte LilycoveCity_DepartmentStore_3F_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_Shop

LilycoveCity_DepartmentStore_4F_MapBorder::
	.incbin "data/maps/LilycoveCity_DepartmentStore_4F/border.bin"

LilycoveCity_DepartmentStore_4F_MapBlockdata::
	.incbin "data/maps/LilycoveCity_DepartmentStore_4F/map.bin"

	.align 2
LilycoveCity_DepartmentStore_4F_MapAttributes::
	.4byte 0x12
	.4byte 0x8
	.4byte LilycoveCity_DepartmentStore_4F_MapBorder
	.4byte LilycoveCity_DepartmentStore_4F_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_Shop

LilycoveCity_DepartmentStore_5F_MapBorder::
	.incbin "data/maps/LilycoveCity_DepartmentStore_5F/border.bin"

LilycoveCity_DepartmentStore_5F_MapBlockdata::
	.incbin "data/maps/LilycoveCity_DepartmentStore_5F/map.bin"

	.align 2
LilycoveCity_DepartmentStore_5F_MapAttributes::
	.4byte 0x12
	.4byte 0x8
	.4byte LilycoveCity_DepartmentStore_5F_MapBorder
	.4byte LilycoveCity_DepartmentStore_5F_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_Shop

LilycoveCity_DepartmentStoreRooftop_MapBorder::
	.incbin "data/maps/LilycoveCity_DepartmentStoreRooftop/border.bin"

LilycoveCity_DepartmentStoreRooftop_MapBlockdata::
	.incbin "data/maps/LilycoveCity_DepartmentStoreRooftop/map.bin"

	.align 2
LilycoveCity_DepartmentStoreRooftop_MapAttributes::
	.4byte 0x12
	.4byte 0xc
	.4byte LilycoveCity_DepartmentStoreRooftop_MapBorder
	.4byte LilycoveCity_DepartmentStoreRooftop_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_Shop

Route130_MapBorder::
	.incbin "data/maps/Route130/border.bin"

Route130_MapBlockdata::
	.incbin "data/maps/Route130/map.bin"

	.align 2
Route130_MapAttributes::
	.4byte 0x50
	.4byte 0x28
	.4byte Route130_MapBorder
	.4byte Route130_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Cave

BattleTower_Lobby_MapBorder::
	.incbin "data/maps/BattleTower_Lobby/border.bin"

BattleTower_Lobby_MapBlockdata::
	.incbin "data/maps/BattleTower_Lobby/map.bin"

	.align 2
BattleTower_Lobby_MapAttributes::
	.4byte 0xe
	.4byte 0x9
	.4byte BattleTower_Lobby_MapBorder
	.4byte BattleTower_Lobby_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_BattleTower

BattleTower_Outside_MapBorder::
	.incbin "data/maps/BattleTower_Outside/border.bin"

BattleTower_Outside_MapBlockdata::
	.incbin "data/maps/BattleTower_Outside/map.bin"

	.align 2
BattleTower_Outside_MapAttributes::
	.4byte 0x1d
	.4byte 0x1e
	.4byte BattleTower_Outside_MapBorder
	.4byte BattleTower_Outside_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Dewford

BattleTower_Elevator_MapBorder::
	.incbin "data/maps/BattleTower_Elevator/border.bin"

BattleTower_Elevator_MapBlockdata::
	.incbin "data/maps/BattleTower_Elevator/map.bin"

	.align 2
BattleTower_Elevator_MapAttributes::
	.4byte 0x4
	.4byte 0x7
	.4byte BattleTower_Elevator_MapBorder
	.4byte BattleTower_Elevator_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_BattleTower

BattleTower_Corridor_MapBorder::
	.incbin "data/maps/BattleTower_Corridor/border.bin"

BattleTower_Corridor_MapBlockdata::
	.incbin "data/maps/BattleTower_Corridor/map.bin"

	.align 2
BattleTower_Corridor_MapAttributes::
	.4byte 0x11
	.4byte 0x5
	.4byte BattleTower_Corridor_MapBorder
	.4byte BattleTower_Corridor_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_BattleTower

BattleTower_BattleRoom_MapBorder::
	.incbin "data/maps/BattleTower_BattleRoom/border.bin"

BattleTower_BattleRoom_MapBlockdata::
	.incbin "data/maps/BattleTower_BattleRoom/map.bin"

	.align 2
BattleTower_BattleRoom_MapAttributes::
	.4byte 0xa
	.4byte 0x9
	.4byte BattleTower_BattleRoom_MapBorder
	.4byte BattleTower_BattleRoom_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_BattleTower

RustboroCity_DevonCorp_3F_MapBorder::
	.incbin "data/maps/RustboroCity_DevonCorp_3F/border.bin"

RustboroCity_DevonCorp_3F_MapBlockdata::
	.incbin "data/maps/RustboroCity_DevonCorp_3F/map.bin"

	.align 2
RustboroCity_DevonCorp_3F_MapAttributes::
	.4byte 0x13
	.4byte 0x9
	.4byte RustboroCity_DevonCorp_3F_MapBorder
	.4byte RustboroCity_DevonCorp_3F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Facility

EverGrandeCity_PokemonLeague_MapBorder::
	.incbin "data/maps/EverGrandeCity_PokemonLeague/border.bin"

EverGrandeCity_PokemonLeague_MapBlockdata::
	.incbin "data/maps/EverGrandeCity_PokemonLeague/map.bin"

	.align 2
EverGrandeCity_PokemonLeague_MapAttributes::
	.4byte 0x13
	.4byte 0xc
	.4byte EverGrandeCity_PokemonLeague_MapBorder
	.4byte EverGrandeCity_PokemonLeague_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_PokemonCenter

Route119_WeatherInstitute_1F_MapBorder::
	.incbin "data/maps/Route119_WeatherInstitute_1F/border.bin"

Route119_WeatherInstitute_1F_MapBlockdata::
	.incbin "data/maps/Route119_WeatherInstitute_1F/map.bin"

	.align 2
Route119_WeatherInstitute_1F_MapAttributes::
	.4byte 0x14
	.4byte 0xd
	.4byte Route119_WeatherInstitute_1F_MapBorder
	.4byte Route119_WeatherInstitute_1F_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_Lab

Route119_WeatherInstitute_2F_MapBorder::
	.incbin "data/maps/Route119_WeatherInstitute_2F/border.bin"

Route119_WeatherInstitute_2F_MapBlockdata::
	.incbin "data/maps/Route119_WeatherInstitute_2F/map.bin"

	.align 2
Route119_WeatherInstitute_2F_MapAttributes::
	.4byte 0x14
	.4byte 0xb
	.4byte Route119_WeatherInstitute_2F_MapBorder
	.4byte Route119_WeatherInstitute_2F_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_Lab

LilycoveCity_DepartmentStoreElevator_MapBorder::
	.incbin "data/maps/LilycoveCity_DepartmentStoreElevator/border.bin"

LilycoveCity_DepartmentStoreElevator_MapBlockdata::
	.incbin "data/maps/LilycoveCity_DepartmentStoreElevator/map.bin"

	.align 2
LilycoveCity_DepartmentStoreElevator_MapAttributes::
	.4byte 0x4
	.4byte 0x6
	.4byte LilycoveCity_DepartmentStoreElevator_MapBorder
	.4byte LilycoveCity_DepartmentStoreElevator_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_BattleTower

Underwater1_MapBorder::
	.incbin "data/maps/Underwater1/border.bin"

Underwater1_MapBlockdata::
	.incbin "data/maps/Underwater1/map.bin"

	.align 2
Underwater1_MapAttributes::
	.4byte 0x50
	.4byte 0x50
	.4byte Underwater1_MapBorder
	.4byte Underwater1_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Underwater

MossdeepCity_SpaceCenter_1F_MapBorder::
	.incbin "data/maps/MossdeepCity_SpaceCenter_1F/border.bin"

MossdeepCity_SpaceCenter_1F_MapBlockdata::
	.incbin "data/maps/MossdeepCity_SpaceCenter_1F/map.bin"

	.align 2
MossdeepCity_SpaceCenter_1F_MapAttributes::
	.4byte 0x10
	.4byte 0xa
	.4byte MossdeepCity_SpaceCenter_1F_MapBorder
	.4byte MossdeepCity_SpaceCenter_1F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Facility

MossdeepCity_SpaceCenter_2F_MapBorder::
	.incbin "data/maps/MossdeepCity_SpaceCenter_2F/border.bin"

MossdeepCity_SpaceCenter_2F_MapBlockdata::
	.incbin "data/maps/MossdeepCity_SpaceCenter_2F/map.bin"

	.align 2
MossdeepCity_SpaceCenter_2F_MapAttributes::
	.4byte 0x10
	.4byte 0xa
	.4byte MossdeepCity_SpaceCenter_2F_MapBorder
	.4byte MossdeepCity_SpaceCenter_2F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Facility

SSTidalCorridor_MapBorder::
	.incbin "data/maps/SSTidalCorridor/border.bin"

SSTidalCorridor_MapBlockdata::
	.incbin "data/maps/SSTidalCorridor/map.bin"

	.align 2
SSTidalCorridor_MapAttributes::
	.4byte 0x12
	.4byte 0xd
	.4byte SSTidalCorridor_MapBorder
	.4byte SSTidalCorridor_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Ship

SSTidalLowerDeck_MapBorder::
	.incbin "data/maps/SSTidalLowerDeck/border.bin"

SSTidalLowerDeck_MapBlockdata::
	.incbin "data/maps/SSTidalLowerDeck/map.bin"

	.align 2
SSTidalLowerDeck_MapAttributes::
	.4byte 0x11
	.4byte 0xd
	.4byte SSTidalLowerDeck_MapBorder
	.4byte SSTidalLowerDeck_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Ship

SSTidalRooms_MapBorder::
	.incbin "data/maps/SSTidalRooms/border.bin"

SSTidalRooms_MapBlockdata::
	.incbin "data/maps/SSTidalRooms/map.bin"

	.align 2
SSTidalRooms_MapAttributes::
	.4byte 0x24
	.4byte 0x12
	.4byte SSTidalRooms_MapBorder
	.4byte SSTidalRooms_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Ship

IslandCave_MapBorder::
	.incbin "data/maps/IslandCave/border.bin"

IslandCave_MapBlockdata::
	.incbin "data/maps/IslandCave/map.bin"

	.align 2
IslandCave_MapAttributes::
	.4byte 0x11
	.4byte 0x21
	.4byte IslandCave_MapBorder
	.4byte IslandCave_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Cave

AncientTomb_MapBorder::
	.incbin "data/maps/AncientTomb/border.bin"

AncientTomb_MapBlockdata::
	.incbin "data/maps/AncientTomb/map.bin"

	.align 2
AncientTomb_MapAttributes::
	.4byte 0x11
	.4byte 0x21
	.4byte AncientTomb_MapBorder
	.4byte AncientTomb_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Cave

Underwater_Route134_MapBorder::
	.incbin "data/maps/Underwater_Route134/border.bin"

Underwater_Route134_MapBlockdata::
	.incbin "data/maps/Underwater_Route134/map.bin"

	.align 2
Underwater_Route134_MapAttributes::
	.4byte 0x12
	.4byte 0xa
	.4byte Underwater_Route134_MapBorder
	.4byte Underwater_Route134_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Underwater

Underwater_SealedChamber_MapBorder::
	.incbin "data/maps/Underwater_SealedChamber/border.bin"

Underwater_SealedChamber_MapBlockdata::
	.incbin "data/maps/Underwater_SealedChamber/map.bin"

	.align 2
Underwater_SealedChamber_MapAttributes::
	.4byte 0x16
	.4byte 0x30
	.4byte Underwater_SealedChamber_MapBorder
	.4byte Underwater_SealedChamber_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Underwater

SealedChamber_OuterRoom_MapBorder::
	.incbin "data/maps/SealedChamber_OuterRoom/border.bin"

SealedChamber_OuterRoom_MapBlockdata::
	.incbin "data/maps/SealedChamber_OuterRoom/map.bin"

	.align 2
SealedChamber_OuterRoom_MapAttributes::
	.4byte 0x15
	.4byte 0x17
	.4byte SealedChamber_OuterRoom_MapBorder
	.4byte SealedChamber_OuterRoom_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Cave

VictoryRoad_B1F_MapBorder::
	.incbin "data/maps/VictoryRoad_B1F/border.bin"

VictoryRoad_B1F_MapBlockdata::
	.incbin "data/maps/VictoryRoad_B1F/map.bin"

	.align 2
VictoryRoad_B1F_MapAttributes::
	.4byte 0x2e
	.4byte 0x1f
	.4byte VictoryRoad_B1F_MapBorder
	.4byte VictoryRoad_B1F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Cave

VictoryRoad_B2F_MapBorder::
	.incbin "data/maps/VictoryRoad_B2F/border.bin"

VictoryRoad_B2F_MapBlockdata::
	.incbin "data/maps/VictoryRoad_B2F/map.bin"

	.align 2
VictoryRoad_B2F_MapAttributes::
	.4byte 0x2e
	.4byte 0x1f
	.4byte VictoryRoad_B2F_MapBorder
	.4byte VictoryRoad_B2F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Cave

Route104_Prototype_MapBorder::
	.incbin "data/maps/Route104_Prototype/border.bin"

Route104_Prototype_MapBlockdata::
	.incbin "data/maps/Route104_Prototype/map.bin"

	.align 2
Route104_Prototype_MapAttributes::
	.4byte 0x1
	.4byte 0x1
	.4byte Route104_Prototype_MapBorder
	.4byte Route104_Prototype_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Rustboro

GraniteCave_StevensRoom_MapBorder::
	.incbin "data/maps/GraniteCave_StevensRoom/border.bin"

GraniteCave_StevensRoom_MapBlockdata::
	.incbin "data/maps/GraniteCave_StevensRoom/map.bin"

	.align 2
GraniteCave_StevensRoom_MapAttributes::
	.4byte 0xf
	.4byte 0xe
	.4byte GraniteCave_StevensRoom_MapBorder
	.4byte GraniteCave_StevensRoom_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Cave

AbandonedShip_HiddenFloorCorridors_MapBorder::
	.incbin "data/maps/AbandonedShip_HiddenFloorCorridors/border.bin"

AbandonedShip_HiddenFloorCorridors_MapBlockdata::
	.incbin "data/maps/AbandonedShip_HiddenFloorCorridors/map.bin"

	.align 2
AbandonedShip_HiddenFloorCorridors_MapAttributes::
	.4byte 0xd
	.4byte 0xb
	.4byte AbandonedShip_HiddenFloorCorridors_MapBorder
	.4byte AbandonedShip_HiddenFloorCorridors_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Ship

SouthernIsland_Exterior_MapBorder::
	.incbin "data/maps/SouthernIsland_Exterior/border.bin"

SouthernIsland_Exterior_MapBlockdata::
	.incbin "data/maps/SouthernIsland_Exterior/map.bin"

	.align 2
SouthernIsland_Exterior_MapAttributes::
	.4byte 0x21
	.4byte 0x1e
	.4byte SouthernIsland_Exterior_MapBorder
	.4byte SouthernIsland_Exterior_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Rustboro

SouthernIsland_Interior_MapBorder::
	.incbin "data/maps/SouthernIsland_Interior/border.bin"

SouthernIsland_Interior_MapBlockdata::
	.incbin "data/maps/SouthernIsland_Interior/map.bin"

	.align 2
SouthernIsland_Interior_MapAttributes::
	.4byte 0x1b
	.4byte 0x18
	.4byte SouthernIsland_Interior_MapBorder
	.4byte SouthernIsland_Interior_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Rustboro

JaggedPass_MapBorder::
	.incbin "data/maps/JaggedPass/border.bin"

JaggedPass_MapBlockdata::
	.incbin "data/maps/JaggedPass/map.bin"

	.align 2
JaggedPass_MapAttributes::
	.4byte 0x1e
	.4byte 0x2e
	.4byte JaggedPass_MapBorder
	.4byte JaggedPass_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Lavaridge

FieryPath_MapBorder::
	.incbin "data/maps/FieryPath/border.bin"

FieryPath_MapBlockdata::
	.incbin "data/maps/FieryPath/map.bin"

	.align 2
FieryPath_MapAttributes::
	.4byte 0x23
	.4byte 0x26
	.4byte FieryPath_MapBorder
	.4byte FieryPath_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Lavaridge

RustboroCity_Flat2_1F_MapBorder::
	.incbin "data/maps/RustboroCity_Flat2_1F/border.bin"

RustboroCity_Flat2_1F_MapBlockdata::
	.incbin "data/maps/RustboroCity_Flat2_1F/map.bin"

	.align 2
RustboroCity_Flat2_1F_MapAttributes::
	.4byte 0xe
	.4byte 0x9
	.4byte RustboroCity_Flat2_1F_MapBorder
	.4byte RustboroCity_Flat2_1F_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_GenericBuilding

RustboroCity_Flat2_2F_MapBorder::
	.incbin "data/maps/RustboroCity_Flat2_2F/border.bin"

RustboroCity_Flat2_2F_MapBlockdata::
	.incbin "data/maps/RustboroCity_Flat2_2F/map.bin"

	.align 2
RustboroCity_Flat2_2F_MapAttributes::
	.4byte 0xe
	.4byte 0x9
	.4byte RustboroCity_Flat2_2F_MapBorder
	.4byte RustboroCity_Flat2_2F_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_GenericBuilding

RustboroCity_Flat2_3F_MapBorder::
	.incbin "data/maps/RustboroCity_Flat2_3F/border.bin"

RustboroCity_Flat2_3F_MapBlockdata::
	.incbin "data/maps/RustboroCity_Flat2_3F/map.bin"

	.align 2
RustboroCity_Flat2_3F_MapAttributes::
	.4byte 0xe
	.4byte 0x9
	.4byte RustboroCity_Flat2_3F_MapBorder
	.4byte RustboroCity_Flat2_3F_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_GenericBuilding

SootopolisCity_House8_MapBorder::
	.incbin "data/maps/SootopolisCity_House8/border.bin"

SootopolisCity_House8_MapBlockdata::
	.incbin "data/maps/SootopolisCity_House8/map.bin"

	.align 2
SootopolisCity_House8_MapAttributes::
	.4byte 0x8
	.4byte 0x7
	.4byte SootopolisCity_House8_MapBorder
	.4byte SootopolisCity_House8_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_GenericBuilding

EverGrandeCity_HallOfFame_MapBorder::
	.incbin "data/maps/EverGrandeCity_HallOfFame/border.bin"

EverGrandeCity_HallOfFame_MapBlockdata::
	.incbin "data/maps/EverGrandeCity_HallOfFame/map.bin"

	.align 2
EverGrandeCity_HallOfFame_MapAttributes::
	.4byte 0xf
	.4byte 0x11
	.4byte EverGrandeCity_HallOfFame_MapBorder
	.4byte EverGrandeCity_HallOfFame_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_CableClub

LilycoveCity_CoveLilyMotel_1F_MapBorder::
	.incbin "data/maps/LilycoveCity_CoveLilyMotel_1F/border.bin"

LilycoveCity_CoveLilyMotel_1F_MapBlockdata::
	.incbin "data/maps/LilycoveCity_CoveLilyMotel_1F/map.bin"

	.align 2
LilycoveCity_CoveLilyMotel_1F_MapAttributes::
	.4byte 0xc
	.4byte 0x9
	.4byte LilycoveCity_CoveLilyMotel_1F_MapBorder
	.4byte LilycoveCity_CoveLilyMotel_1F_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_GenericBuilding

LilycoveCity_CoveLilyMotel_2F_MapBorder::
	.incbin "data/maps/LilycoveCity_CoveLilyMotel_2F/border.bin"

LilycoveCity_CoveLilyMotel_2F_MapBlockdata::
	.incbin "data/maps/LilycoveCity_CoveLilyMotel_2F/map.bin"

	.align 2
LilycoveCity_CoveLilyMotel_2F_MapAttributes::
	.4byte 0xc
	.4byte 0x9
	.4byte LilycoveCity_CoveLilyMotel_2F_MapBorder
	.4byte LilycoveCity_CoveLilyMotel_2F_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_GenericBuilding

Route124_DivingTreasureHuntersHouse_MapBorder::
	.incbin "data/maps/Route124_DivingTreasureHuntersHouse/border.bin"

Route124_DivingTreasureHuntersHouse_MapBlockdata::
	.incbin "data/maps/Route124_DivingTreasureHuntersHouse/map.bin"

	.align 2
Route124_DivingTreasureHuntersHouse_MapAttributes::
	.4byte 0xa
	.4byte 0x9
	.4byte Route124_DivingTreasureHuntersHouse_MapBorder
	.4byte Route124_DivingTreasureHuntersHouse_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_GenericBuilding

MtPyre_Exterior_MapBorder::
	.incbin "data/maps/MtPyre_Exterior/border.bin"

MtPyre_Exterior_MapBlockdata::
	.incbin "data/maps/MtPyre_Exterior/map.bin"

	.align 2
MtPyre_Exterior_MapAttributes::
	.4byte 0x26
	.4byte 0x33
	.4byte MtPyre_Exterior_MapBorder
	.4byte MtPyre_Exterior_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Facility

MtPyre_Summit_MapBorder::
	.incbin "data/maps/MtPyre_Summit/border.bin"

MtPyre_Summit_MapBlockdata::
	.incbin "data/maps/MtPyre_Summit/map.bin"

	.align 2
MtPyre_Summit_MapAttributes::
	.4byte 0x32
	.4byte 0x25
	.4byte MtPyre_Summit_MapBorder
	.4byte MtPyre_Summit_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Facility

SealedChamber_InnerRoom_MapBorder::
	.incbin "data/maps/SealedChamber_InnerRoom/border.bin"

SealedChamber_InnerRoom_MapBlockdata::
	.incbin "data/maps/SealedChamber_InnerRoom/map.bin"

	.align 2
SealedChamber_InnerRoom_MapAttributes::
	.4byte 0x15
	.4byte 0x17
	.4byte SealedChamber_InnerRoom_MapBorder
	.4byte SealedChamber_InnerRoom_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Cave

MossdeepCity_GameCorner_1F_MapBorder::
	.incbin "data/maps/MossdeepCity_GameCorner_1F/border.bin"

MossdeepCity_GameCorner_1F_MapBlockdata::
	.incbin "data/maps/MossdeepCity_GameCorner_1F/map.bin"

	.align 2
MossdeepCity_GameCorner_1F_MapAttributes::
	.4byte 0xb
	.4byte 0x8
	.4byte MossdeepCity_GameCorner_1F_MapBorder
	.4byte MossdeepCity_GameCorner_1F_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_GenericBuilding

MossdeepCity_GameCorner_B1F_MapBorder::
	.incbin "data/maps/MossdeepCity_GameCorner_B1F/border.bin"

MossdeepCity_GameCorner_B1F_MapBlockdata::
	.incbin "data/maps/MossdeepCity_GameCorner_B1F/map.bin"

	.align 2
MossdeepCity_GameCorner_B1F_MapAttributes::
	.4byte 0xc
	.4byte 0x9
	.4byte MossdeepCity_GameCorner_B1F_MapBorder
	.4byte MossdeepCity_GameCorner_B1F_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_GenericBuilding

SootopolisCity_House1_MapBorder::
	.incbin "data/maps/SootopolisCity_House1/border.bin"

SootopolisCity_House1_MapBlockdata::
	.incbin "data/maps/SootopolisCity_House1/map.bin"

	.align 2
SootopolisCity_House1_MapAttributes::
SootopolisCity_House4_MapAttributes::
SootopolisCity_House7_MapAttributes::
	.4byte 0x8
	.4byte 0x7
	.4byte SootopolisCity_House1_MapBorder
	.4byte SootopolisCity_House1_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_GenericBuilding

SootopolisCity_House2_MapBorder::
	.incbin "data/maps/SootopolisCity_House2/border.bin"

SootopolisCity_House2_MapBlockdata::
	.incbin "data/maps/SootopolisCity_House2/map.bin"

	.align 2
SootopolisCity_House2_MapAttributes::
SootopolisCity_House5_MapAttributes::
	.4byte 0x8
	.4byte 0x7
	.4byte SootopolisCity_House2_MapBorder
	.4byte SootopolisCity_House2_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_GenericBuilding

SootopolisCity_House3_MapBorder::
	.incbin "data/maps/SootopolisCity_House3/border.bin"

SootopolisCity_House3_MapBlockdata::
	.incbin "data/maps/SootopolisCity_House3/map.bin"

	.align 2
SootopolisCity_House3_MapAttributes::
SootopolisCity_House6_MapAttributes::
	.4byte 0x8
	.4byte 0x7
	.4byte SootopolisCity_House3_MapBorder
	.4byte SootopolisCity_House3_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_GenericBuilding

AbandonedShip_HiddenFloorRooms_MapBorder::
	.incbin "data/maps/AbandonedShip_HiddenFloorRooms/border.bin"

AbandonedShip_HiddenFloorRooms_MapBlockdata::
	.incbin "data/maps/AbandonedShip_HiddenFloorRooms/map.bin"

	.align 2
AbandonedShip_HiddenFloorRooms_MapAttributes::
	.4byte 0x2c
	.4byte 0xf
	.4byte AbandonedShip_HiddenFloorRooms_MapBorder
	.4byte AbandonedShip_HiddenFloorRooms_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Ship

ScorchedSlab_MapBorder::
	.incbin "data/maps/ScorchedSlab/border.bin"

ScorchedSlab_MapBlockdata::
	.incbin "data/maps/ScorchedSlab/map.bin"

	.align 2
ScorchedSlab_MapAttributes::
	.4byte 0xf
	.4byte 0x14
	.4byte ScorchedSlab_MapBorder
	.4byte ScorchedSlab_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Cave

UnknownMapBorder_082FF894::
	.incbin "data/maps/UnknownMap_082FF894/border.bin"

UnknownMapBlockdata_082FF894::
	.incbin "data/maps/UnknownMap_082FF894/map.bin"

	.align 2
UnknownMapAttributes_082FF894::
	.4byte 0x13
	.4byte 0x13
	.4byte UnknownMapBorder_082FF894
	.4byte UnknownMapBlockdata_082FF894
	.4byte gTileset_General
	.4byte gTileset_Cave

RustboroCity_Flat1_1F_MapBorder::
	.incbin "data/maps/RustboroCity_Flat1_1F/border.bin"

RustboroCity_Flat1_1F_MapBlockdata::
	.incbin "data/maps/RustboroCity_Flat1_1F/map.bin"

	.align 2
RustboroCity_Flat1_1F_MapAttributes::
	.4byte 0xe
	.4byte 0x8
	.4byte RustboroCity_Flat1_1F_MapBorder
	.4byte RustboroCity_Flat1_1F_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_GenericBuilding

RustboroCity_Flat1_2F_MapBorder::
	.incbin "data/maps/RustboroCity_Flat1_2F/border.bin"

RustboroCity_Flat1_2F_MapBlockdata::
	.incbin "data/maps/RustboroCity_Flat1_2F/map.bin"

	.align 2
RustboroCity_Flat1_2F_MapAttributes::
	.4byte 0xe
	.4byte 0x8
	.4byte RustboroCity_Flat1_2F_MapBorder
	.4byte RustboroCity_Flat1_2F_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_GenericBuilding

EverGrandeCity_Corridor4_MapBorder::
	.incbin "data/maps/EverGrandeCity_Corridor4/border.bin"

EverGrandeCity_Corridor4_MapBlockdata::
	.incbin "data/maps/EverGrandeCity_Corridor4/map.bin"

	.align 2
EverGrandeCity_Corridor4_MapAttributes::
	.4byte 0xb
	.4byte 0x22
	.4byte EverGrandeCity_Corridor4_MapBorder
	.4byte EverGrandeCity_Corridor4_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_EliteFour

MagmaHideout_1F_MapBorder::
	.incbin "data/maps/MagmaHideout_1F/border.bin"

MagmaHideout_1F_MapBlockdata::
	.incbin "data/maps/MagmaHideout_1F/map.bin"

	.align 2
MagmaHideout_1F_MapAttributes::
	.4byte 0x1c
	.4byte 0x1e
	.4byte MagmaHideout_1F_MapBorder
	.4byte MagmaHideout_1F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Facility

MagmaHideout_B1F_MapBorder::
	.incbin "data/maps/MagmaHideout_B1F/border.bin"

MagmaHideout_B1F_MapBlockdata::
	.incbin "data/maps/MagmaHideout_B1F/map.bin"

	.align 2
MagmaHideout_B1F_MapAttributes::
	.4byte 0x3e
	.4byte 0x18
	.4byte MagmaHideout_B1F_MapBorder
	.4byte MagmaHideout_B1F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Facility

MagmaHideout_B2F_MapBorder::
	.incbin "data/maps/MagmaHideout_B2F/border.bin"

MagmaHideout_B2F_MapBlockdata::
	.incbin "data/maps/MagmaHideout_B2F/map.bin"

	.align 2
MagmaHideout_B2F_MapAttributes::
	.4byte 0x22
	.4byte 0x18
	.4byte MagmaHideout_B2F_MapBorder
	.4byte MagmaHideout_B2F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Facility

UnknownMapBorder_08302970::
	.incbin "data/maps/UnknownMap_08302970/border.bin"

UnknownMapBlockdata_08302970::
	.incbin "data/maps/UnknownMap_08302970/map.bin"

	.align 2
UnknownMapAttributes_08302970::
	.4byte 0x3C
	.4byte 0x28
	.4byte UnknownMapBorder_08302970
	.4byte UnknownMapBlockdata_08302970
	.4byte gTileset_General
	.4byte gTileset_Pacifidlog

SkyPillar_Entrance_MapBorder::
	.incbin "data/maps/SkyPillar_Entrance/border.bin"

SkyPillar_Entrance_MapBlockdata::
	.incbin "data/maps/SkyPillar_Entrance/map.bin"

	.align 2
SkyPillar_Entrance_MapAttributes::
	.4byte 0x12
	.4byte 0x12
	.4byte SkyPillar_Entrance_MapBorder
	.4byte SkyPillar_Entrance_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Cave

SkyPillar_Outside_MapBorder::
	.incbin "data/maps/SkyPillar_Outside/border.bin"

SkyPillar_Outside_MapBlockdata::
	.incbin "data/maps/SkyPillar_Outside/map.bin"

	.align 2
SkyPillar_Outside_MapAttributes::
	.4byte 0x1c
	.4byte 0x17
	.4byte SkyPillar_Outside_MapBorder
	.4byte SkyPillar_Outside_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Pacifidlog

SkyPillar_1F_MapBorder::
	.incbin "data/maps/SkyPillar_1F/border.bin"

SkyPillar_1F_MapBlockdata::
	.incbin "data/maps/SkyPillar_1F/map.bin"

	.align 2
SkyPillar_1F_MapAttributes::
	.4byte 0xe
	.4byte 0xe
	.4byte SkyPillar_1F_MapBorder
	.4byte SkyPillar_1F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Pacifidlog

SkyPillar_2F_MapBorder::
	.incbin "data/maps/SkyPillar_2F/border.bin"

SkyPillar_2F_MapBlockdata::
	.incbin "data/maps/SkyPillar_2F/map.bin"

	.align 2
SkyPillar_2F_MapAttributes::
	.4byte 0xe
	.4byte 0xe
	.4byte SkyPillar_2F_MapBorder
	.4byte SkyPillar_2F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Pacifidlog

SkyPillar_3F_MapBorder::
	.incbin "data/maps/SkyPillar_3F/border.bin"

SkyPillar_3F_MapBlockdata::
	.incbin "data/maps/SkyPillar_3F/map.bin"

	.align 2
SkyPillar_3F_MapAttributes::
	.4byte 0xe
	.4byte 0xe
	.4byte SkyPillar_3F_MapBorder
	.4byte SkyPillar_3F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Pacifidlog

SkyPillar_4F_MapBorder::
	.incbin "data/maps/SkyPillar_4F/border.bin"

SkyPillar_4F_MapBlockdata::
	.incbin "data/maps/SkyPillar_4F/map.bin"

	.align 2
SkyPillar_4F_MapAttributes::
	.4byte 0xe
	.4byte 0xe
	.4byte SkyPillar_4F_MapBorder
	.4byte SkyPillar_4F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Pacifidlog

UnknownMapBorder_083041B4::
	.incbin "data/maps/UnknownMap_083041B4/border.bin"

UnknownMapBlockdata_083041B4::
	.incbin "data/maps/UnknownMap_083041B4/map.bin"

	.align 2
UnknownMapAttributes_083041B4::
	.4byte 0x1B
	.4byte 0x2E
	.4byte UnknownMapBorder_083041B4
	.4byte UnknownMapBlockdata_083041B4
	.4byte gTileset_General
	.4byte gTileset_Cave

MossdeepCity_StevensHouse_MapBorder::
	.incbin "data/maps/MossdeepCity_StevensHouse/border.bin"

MossdeepCity_StevensHouse_MapBlockdata::
	.incbin "data/maps/MossdeepCity_StevensHouse/map.bin"

	.align 2
MossdeepCity_StevensHouse_MapAttributes::
	.4byte 0xb
	.4byte 0x8
	.4byte MossdeepCity_StevensHouse_MapBorder
	.4byte MossdeepCity_StevensHouse_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_GenericBuilding

ShoalCave_LowTideIceRoom_MapBorder::
	.incbin "data/maps/ShoalCave_LowTideIceRoom/border.bin"

ShoalCave_LowTideIceRoom_MapBlockdata::
	.incbin "data/maps/ShoalCave_LowTideIceRoom/map.bin"

	.align 2
ShoalCave_LowTideIceRoom_MapAttributes::
	.4byte 0x14
	.4byte 0x1e
	.4byte ShoalCave_LowTideIceRoom_MapBorder
	.4byte ShoalCave_LowTideIceRoom_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Cave

SafariZone_RestHouse_MapBorder::
	.incbin "data/maps/SafariZone_RestHouse/border.bin"

SafariZone_RestHouse_MapBlockdata::
	.incbin "data/maps/SafariZone_RestHouse/map.bin"

	.align 2
SafariZone_RestHouse_MapAttributes::
	.4byte 0xa
	.4byte 0x9
	.4byte SafariZone_RestHouse_MapBorder
	.4byte SafariZone_RestHouse_MapBlockdata
	.4byte gTileset_Building
	.4byte gTileset_GenericBuilding

SkyPillar_5F_MapBorder::
	.incbin "data/maps/SkyPillar_5F/border.bin"

SkyPillar_5F_MapBlockdata::
	.incbin "data/maps/SkyPillar_5F/map.bin"

	.align 2
SkyPillar_5F_MapAttributes::
	.4byte 0xe
	.4byte 0xe
	.4byte SkyPillar_5F_MapBorder
	.4byte SkyPillar_5F_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Pacifidlog

SkyPillar_Top_MapBorder::
	.incbin "data/maps/SkyPillar_Top/border.bin"

SkyPillar_Top_MapBlockdata::
	.incbin "data/maps/SkyPillar_Top/map.bin"

	.align 2
SkyPillar_Top_MapAttributes::
	.4byte 0x1b
	.4byte 0x18
	.4byte SkyPillar_Top_MapBorder
	.4byte SkyPillar_Top_MapBlockdata
	.4byte gTileset_General
	.4byte gTileset_Pacifidlog

